In [70]:
import pandas as pd
import re
import numpy as np

In [71]:
df = pd.read_excel("BOQ_1833226.xls", skiprows=10)

In [72]:
print(df.columns.tolist())

['Sl.\nNo.', 'Item Description', 'Item Code / Make', 'Quantity', 'Units', 'Estimated Rate in \nRs.     P', 'Unnamed: 6', 'Unnamed: 7', 'Addition / Deduction', 'Addition / Deduction Values', 'Currency Convertion against each Item', 'Quoted Currency in INR / Other Currency', 'BASIC RATE In Figures To be entered by the Bidder \nRs.      P\n ', 'Excise Duty', 'VAT', 'Freight Charges ( Unloading & Stacking)', 'Any Other Taxes/Duties/Levies', 'Unnamed: 17', 'Unnamed: 18', 'Other Taxes 2', 'IIIrd Party i.e DGS&D / RITES etc Inspection Charges @0.34%+Service Tax', 'Less for Cenvat Credit,if any respect of Supplies Under full Excise Duty Category ', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'TOTAL AMOUNT  Without Taxes in \nRs.     P', 'TOTAL AMOUNT  With Taxes in \nRs.     P', 'TOTAL AMOUNT \nIn Words', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129', 'Unnamed: 130', 'Unnamed: 131', 'Unnamed: 132', 'Unnamed: 133', 'Unnamed: 134', 'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'Unnamed: 138', 'Unnamed: 139', 'Unnamed: 140', 'Unnamed: 141', 'Unnamed: 142', 'Unnamed: 143', 'Unnamed: 144', 'Unnamed: 145', 'Unnamed: 146', 'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'Unnamed: 150', 'Unnamed: 151', 'Unnamed: 152', 'Unnamed: 153', 'Unnamed: 154', 'Unnamed: 155', 'Unnamed: 156', 'Unnamed: 157', 'Unnamed: 158', 'Unnamed: 159', 'Unnamed: 160', 'Unnamed: 161', 'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169', 'Unnamed: 170', 'Unnamed: 171', 'Unnamed: 172', 'Unnamed: 173', 'Unnamed: 174', 'Unnamed: 175', 'Unnamed: 176', 'Unnamed: 177', 'Unnamed: 178', 'Unnamed: 179', 'Unnamed: 180', 'Unnamed: 181', 'Unnamed: 182', 'Unnamed: 183', 'Unnamed: 184', 'Unnamed: 185', 'Unnamed: 186', 'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190', 'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194', 'Unnamed: 195', 'Unnamed: 196', 'Unnamed: 197', 'Unnamed: 198', 'Unnamed: 199', 'Unnamed: 200', 'Unnamed: 201', 'Unnamed: 202', 'Unnamed: 203', 'Unnamed: 204', 'Unnamed: 205', 'Unnamed: 206', 'Unnamed: 207', 'Unnamed: 208', 'Unnamed: 209', 'Unnamed: 210', 'Unnamed: 211', 'Unnamed: 212', 'Unnamed: 213', 'Unnamed: 214', 'Unnamed: 215', 'Unnamed: 216', 'Unnamed: 217', 'Unnamed: 218', 'Unnamed: 219', 'Unnamed: 220', 'Unnamed: 221', 'Unnamed: 222', 'Unnamed: 223', 'Unnamed: 224', 'Unnamed: 225', 'Unnamed: 226', 'Unnamed: 227', 'Unnamed: 228', 'Unnamed: 229', 'Unnamed: 230', 'Unnamed: 231', 'Unnamed: 232', 'Unnamed: 233', 'Unnamed: 234', 'Unnamed: 235', 'Unnamed: 236', 'Unnamed: 237', 'Unnamed: 238', 'Unnamed: 239', 'Unnamed: 240', 'Unnamed: 241', 'Unnamed: 242']

In [73]:
columns_to_keep = [
    "Item Description",
    "Item Code / Make",
    "Quantity",
    "Units",
    "Estimated Rate in Rs. P"  ]

In [74]:

for col in df.columns:
    print(repr(col))

'Sl.\nNo.'
'Item Description'
'Item Code / Make'
'Quantity'
'Units'
'Estimated Rate in \nRs.     P'
'Unnamed: 6'
'Unnamed: 7'
'Addition / Deduction'
'Addition / Deduction Values'
'Currency Convertion against each Item'
'Quoted Currency in INR / Other Currency'
'BASIC RATE In Figures To be entered by the Bidder \nRs.      P\n '
'Excise Duty'
'VAT'
'Freight Charges ( Unloading & Stacking)'
'Any Other Taxes/Duties/Levies'
'Unnamed: 17'
'Unnamed: 18'
'Other Taxes 2'
'IIIrd Party i.e DGS&D / RITES etc Inspection Charges @0.34%+Service Tax'
'Less for Cenvat Credit,if any respect of Supplies Under full Excise Duty Category '
'Unnamed: 22'
'Unnamed: 23'
'Unnamed: 24'
'Unnamed: 25'
'Unnamed: 26'
'Unnamed: 27'
'Unnamed: 28'
'Unnamed: 29'
'Unnamed: 30'
'Unnamed: 31'
'Unnamed: 32'
'Unnamed: 33'
'Unnamed: 34'
'Unnamed: 35'
'Unnamed: 36'
'Unnamed: 37'
'Unnamed: 38'
'Unnamed: 39'
'Unnamed: 40'
'Unnamed: 41'
'Unnamed: 42'
'Unnamed: 43'
'Unnamed: 44'
'Unnamed: 45'
'Unnamed: 46'
'Unnamed: 47'
'Unnamed: 48'
'Unnamed: 49'
'Unnamed: 50'
'Unnamed: 51'
'TOTAL AMOUNT  Without Taxes in \nRs.     P'
'TOTAL AMOUNT  With Taxes in \nRs.     P'
'TOTAL AMOUNT \nIn Words'
'Unnamed: 55'
'Unnamed: 56'
'Unnamed: 57'
'Unnamed: 58'
'Unnamed: 59'
'Unnamed: 60'
'Unnamed: 61'
'Unnamed: 62'
'Unnamed: 63'
'Unnamed: 64'
'Unnamed: 65'
'Unnamed: 66'
'Unnamed: 67'
'Unnamed: 68'
'Unnamed: 69'
'Unnamed: 70'
'Unnamed: 71'
'Unnamed: 72'
'Unnamed: 73'
'Unnamed: 74'
'Unnamed: 75'
'Unnamed: 76'
'Unnamed: 77'
'Unnamed: 78'
'Unnamed: 79'
'Unnamed: 80'
'Unnamed: 81'
'Unnamed: 82'
'Unnamed: 83'
'Unnamed: 84'
'Unnamed: 85'
'Unnamed: 86'
'Unnamed: 87'
'Unnamed: 88'
'Unnamed: 89'
'Unnamed: 90'
'Unnamed: 91'
'Unnamed: 92'
'Unnamed: 93'
'Unnamed: 94'
'Unnamed: 95'
'Unnamed: 96'
'Unnamed: 97'
'Unnamed: 98'
'Unnamed: 99'
'Unnamed: 100'
'Unnamed: 101'
'Unnamed: 102'
'Unnamed: 103'
'Unnamed: 104'
'Unnamed: 105'
'Unnamed: 106'
'Unnamed: 107'
'Unnamed: 108'
'Unnamed: 109'
'Unnamed: 110'
'Unnamed: 111'
'Unnamed: 112'
'Unnamed: 113'
'Unnamed: 114'
'Unnamed: 115'
'Unnamed: 116'
'Unnamed: 117'
'Unnamed: 118'
'Unnamed: 119'
'Unnamed: 120'
'Unnamed: 121'
'Unnamed: 122'
'Unnamed: 123'
'Unnamed: 124'
'Unnamed: 125'
'Unnamed: 126'
'Unnamed: 127'
'Unnamed: 128'
'Unnamed: 129'
'Unnamed: 130'
'Unnamed: 131'
'Unnamed: 132'
'Unnamed: 133'
'Unnamed: 134'
'Unnamed: 135'
'Unnamed: 136'
'Unnamed: 137'
'Unnamed: 138'
'Unnamed: 139'
'Unnamed: 140'
'Unnamed: 141'
'Unnamed: 142'
'Unnamed: 143'
'Unnamed: 144'
'Unnamed: 145'
'Unnamed: 146'
'Unnamed: 147'
'Unnamed: 148'
'Unnamed: 149'
'Unnamed: 150'
'Unnamed: 151'
'Unnamed: 152'
'Unnamed: 153'
'Unnamed: 154'
'Unnamed: 155'
'Unnamed: 156'
'Unnamed: 157'
'Unnamed: 158'
'Unnamed: 159'
'Unnamed: 160'
'Unnamed: 161'
'Unnamed: 162'
'Unnamed: 163'
'Unnamed: 164'
'Unnamed: 165'
'Unnamed: 166'
'Unnamed: 167'
'Unnamed: 168'
'Unnamed: 169'
'Unnamed: 170'
'Unnamed: 171'
'Unnamed: 172'
'Unnamed: 173'
'Unnamed: 174'
'Unnamed: 175'
'Unnamed: 176'
'Unnamed: 177'
'Unnamed: 178'
'Unnamed: 179'
'Unnamed: 180'
'Unnamed: 181'
'Unnamed: 182'
'Unnamed: 183'
'Unnamed: 184'
'Unnamed: 185'
'Unnamed: 186'
'Unnamed: 187'
'Unnamed: 188'
'Unnamed: 189'
'Unnamed: 190'
'Unnamed: 191'
'Unnamed: 192'
'Unnamed: 193'
'Unnamed: 194'
'Unnamed: 195'
'Unnamed: 196'
'Unnamed: 197'
'Unnamed: 198'
'Unnamed: 199'
'Unnamed: 200'
'Unnamed: 201'
'Unnamed: 202'
'Unnamed: 203'
'Unnamed: 204'
'Unnamed: 205'
'Unnamed: 206'
'Unnamed: 207'
'Unnamed: 208'
'Unnamed: 209'
'Unnamed: 210'
'Unnamed: 211'
'Unnamed: 212'
'Unnamed: 213'
'Unnamed: 214'
'Unnamed: 215'
'Unnamed: 216'
'Unnamed: 217'
'Unnamed: 218'
'Unnamed: 219'
'Unnamed: 220'
'Unnamed: 221'
'Unnamed: 222'
'Unnamed: 223'
'Unnamed: 224'
'Unnamed: 225'
'Unnamed: 226'
'Unnamed: 227'
'Unnamed: 228'
'Unnamed: 229'
'Unnamed: 230'
'Unnamed: 231'
'Unnamed: 232'
'Unnamed: 233'
'Unnamed: 234'
'Unnamed: 235'
'Unnamed: 236'
'Unnamed: 237'
'Unnamed: 238'
'Unnamed: 239'
'Unnamed: 240'
'Unnamed: 241'
'Unnamed: 242'

In [75]:
filtered_df.head(20)

,Item Description,Item Code / Make,Quantity,Units,Estimated Rate in \nRs. P
0,2,3,4.0,5,6.00
1,Cost for DI K-9 & M.S Pipes with Fittings & Va...,BI01010001010000000000000515BI0100001112,NaN,NaN,NaN
2,Carrying CI/DI pipes with specials and valves ...,BI01010001010000000000000515BI0100001113,4905.0,Mtr.,112.00
3,200 mm dia Pipe,BI01010001010000000000000515BI0100001114,3420.0,Mtr.,136.00
4,250 mm dia Pipe,BI01010001010000000000000515BI0100001115,2040.0,Mtr.,164.00
5,300 mm dia Pipe,BI01010001010000000000000515BI0100001116,267.5,Mtr.,192.00
6,"Filling the pipe line with water, testing hydr...",BI01010001010000000000000515BI0100001117,4955.0,Mtr.,4.20
7,200 mm dia Pipe,BI01010001010000000000000515BI0100001118,3455.0,Mtr.,5.61
8,250 mm dia Pipe,BI01010001010000000000000515BI0100001119,2060.0,Mtr.,6.66
9,300 mm dia Pipe,BI01010001010000000000000515BI0100001120,270.0,Mtr.,7.22
10,Cleaning thoroughly the inner surface of pipe ...,BI01010001010000000000000515BI0100001121,4955.0,Mtr.,1.54
11,200 mm dia Pipe,BI01010001010000000000000515BI0100001122,3455.0,Mtr.,2.38
12,250 mm dia Pipe,BI01010001010000000000000515BI0100001123,2060.0,Mtr.,3.47
13,300 mm dia Pipe,BI01010001010000000000000515BI0100001124,270.0,Mtr.,4.80
14,Cutting DI pipe (all class & type) to required...,BI01010001010000000000000515BI0100001125,84.0,Each,141.00
15,c) 250mm.dia.to 350mm.dia pipe,BI01010001010000000000000515BI0100001126,23.0,Each,263.00
16,Chamfering the spigot end of all type/class of...,BI01010001010000000000000515BI0100001127,100.0,Each,108.00
17,200 mm dia Pipe,BI01010001010000000000000515BI0100001128,70.0,Each,113.00
18,250 mm dia Pipe,BI01010001010000000000000515BI0100001129,42.0,Each,120.00
19,300 mm dia Pipe,BI01010001010000000000000515BI0100001130,6.0,Each,160.00

In [76]:
df.columns = df.columns.str.strip()

In [90]:
df = pd.read_excel("BOQ_1833226.xls", skiprows=10)

In [91]:
df.columns = df.columns.str.strip()

In [92]:
rate_col = next((col for col in df.columns if "Estimated Rate" in col), None)

In [93]:
df = df[df['Units'].astype(str).str.strip().str.lower() == 'mtr.']

In [94]:
def extract_class(desc):
    desc = str(desc).upper()
    if 'K-9' in desc or 'K9' in desc:
        return 'K9'
    elif 'K-7' in desc or 'K7' in desc:
        return 'K7'
    elif 'M.S' in desc or 'MS' in desc:
        return 'M.S'
    elif 'DI' in desc:
        return 'DI'
    elif 'CI' in desc:
        return 'CI'
    else:
        return 'Other'

In [95]:
def extract_dia(desc):
    desc = str(desc)
    match = re.search(r'(\d{2,4})\s*mm', desc)
    return match.group(1) if match else ''

In [96]:
df['class'] = df['Item Description'].apply(extract_class)
df['DIA'] = df['Item Description'].apply(extract_dia)

In [97]:
df = df.rename(columns={rate_col: 'estimate rate'})

In [98]:
final_df = df[['Item Description', 'Item Code / Make', 'class', 'DIA', 'estimate rate', 'Units']]

In [101]:
print(final_df.head())

                                    Item Description  \
2  Carrying CI/DI pipes with specials and valves ...
3                                   200 mm dia  Pipe
4                                   250 mm dia  Pipe
5                                   300 mm dia  Pipe
6  Filling the pipe line with water, testing hydr...

                           Item Code / Make class  DIA  estimate rate Units
2  BI01010001010000000000000515BI0100001113    DI  150          112.0  Mtr.
3  BI01010001010000000000000515BI0100001114    DI  200          136.0  Mtr.
4  BI01010001010000000000000515BI0100001115    DI  250          164.0  Mtr.
5  BI01010001010000000000000515BI0100001116    DI  300          192.0  Mtr.
6  BI01010001010000000000000515BI0100001117    DI  150            4.2  Mtr.

In [102]:
final_df = final_df.drop(columns=['Item Code / Make'])

In [104]:
final_df.head(20)

,Item Description,class,DIA,estimate rate,Units
2,Carrying CI/DI pipes with specials and valves ...,DI,150,112.00,Mtr.
3,200 mm dia Pipe,DI,200,136.00,Mtr.
4,250 mm dia Pipe,DI,250,164.00,Mtr.
5,300 mm dia Pipe,DI,300,192.00,Mtr.
6,"Filling the pipe line with water, testing hydr...",DI,150,4.20,Mtr.
7,200 mm dia Pipe,DI,200,5.61,Mtr.
8,250 mm dia Pipe,DI,250,6.66,Mtr.
9,300 mm dia Pipe,DI,300,7.22,Mtr.
10,Cleaning thoroughly the inner surface of pipe ...,DI,150,1.54,Mtr.
11,200 mm dia Pipe,DI,200,2.38,Mtr.
12,250 mm dia Pipe,DI,250,3.47,Mtr.
13,300 mm dia Pipe,DI,300,4.80,Mtr.
43,Submission of complete detailed drawing of dis...,DI,,0.38,Mtr.
44,Making barricading of excavation trenches of r...,DI,75,118.00,Mtr.
49,Laying Cost of M.S pipe \n150 mm dia Pipe,M.S,150,564.38,Mtr.
50,200 mm dia Pipe,DI,200,929.52,Mtr.
51,250 mm dia Pipe,DI,250,1118.23,Mtr.
52,300 mm dia Pipe,DI,300,1755.08,Mtr.
55,Supply & Delivery (at Site) of DI K-9 Pipes co...,K9,150,2161.00,Mtr.
56,200 mm dia Pipe,DI,200,2881.00,Mtr.

In [106]:
descriptions_to_remove = [
    "Filling the pipe line with water",
    "200 mm dia Pipe",  
    "250 mm dia Pipe",
    "300 mm dia Pipe",
    "Cleaning thoroughly the inner surface of pipe",
    "Submission of complete detailed drawing of dis",
    "Making barricading of excavation trenches"
]

In [107]:
filtered_df = final_df[~final_df['Item Description'].astype(str).str.startswith(tuple(descriptions_to_remove))]

In [112]:
print(filtered_df.head(20))

                                     Item Description class  DIA  \
2   Carrying CI/DI pipes with specials and valves ...    DI  150
3                                    200 mm dia  Pipe    DI  200
4                                    250 mm dia  Pipe    DI  250
5                                    300 mm dia  Pipe    DI  300
7                                    200 mm dia  Pipe    DI  200
8                                    250 mm dia  Pipe    DI  250
9                                    300 mm dia  Pipe    DI  300
11                                   200 mm dia  Pipe    DI  200
12                                   250 mm dia  Pipe    DI  250
13                                   300 mm dia  Pipe    DI  300
49         Laying Cost of M.S pipe \n150 mm dia  Pipe   M.S  150
50                                   200 mm dia  Pipe    DI  200
51                                   250 mm dia  Pipe    DI  250
52                                   300 mm dia  Pipe    DI  300
55  Supply & Delivery (at Site) of DI K-9 Pipes co...    K9  150
56                                   200 mm dia  Pipe    DI  200
57                                   250 mm dia  Pipe    DI  250
58                                   300 mm dia  Pipe    DI  300
59  Supply of M.S pipe Including Coating including...   M.S  150
60                                   200 mm dia  Pipe    DI  200

    estimate rate Units
2          112.00  Mtr.
3          136.00  Mtr.
4          164.00  Mtr.
5          192.00  Mtr.
7            5.61  Mtr.
8            6.66  Mtr.
9            7.22  Mtr.
11           2.38  Mtr.
12           3.47  Mtr.
13           4.80  Mtr.
49         564.38  Mtr.
50         929.52  Mtr.
51        1118.23  Mtr.
52        1755.08  Mtr.
55        2161.00  Mtr.
56        2881.00  Mtr.
57        3857.00  Mtr.
58        4887.00  Mtr.
59        2505.19  Mtr.
60        3812.56  Mtr.

In [113]:
filtered_df = final_df[final_df['estimate rate'] >= 100]

In [114]:
filtered_df

,Item Description,class,DIA,estimate rate,Units
2,Carrying CI/DI pipes with specials and valves ...,DI,150,112.00,Mtr.
3,200 mm dia Pipe,DI,200,136.00,Mtr.
4,250 mm dia Pipe,DI,250,164.00,Mtr.
5,300 mm dia Pipe,DI,300,192.00,Mtr.
44,Making barricading of excavation trenches of r...,DI,75,118.00,Mtr.
49,Laying Cost of M.S pipe \n150 mm dia Pipe,M.S,150,564.38,Mtr.
50,200 mm dia Pipe,DI,200,929.52,Mtr.
51,250 mm dia Pipe,DI,250,1118.23,Mtr.
52,300 mm dia Pipe,DI,300,1755.08,Mtr.
55,Supply & Delivery (at Site) of DI K-9 Pipes co...,K9,150,2161.00,Mtr.
56,200 mm dia Pipe,DI,200,2881.00,Mtr.
57,250 mm dia Pipe,DI,250,3857.00,Mtr.
58,300 mm dia Pipe,DI,300,4887.00,Mtr.
59,Supply of M.S pipe Including Coating including...,M.S,150,2505.19,Mtr.
60,200 mm dia Pipe,DI,200,3812.56,Mtr.
61,250 mm dia Pipe,DI,250,4398.50,Mtr.
62,300 mm dia Pipe,DI,300,5714.49,Mtr.

In [115]:
descriptions_to_remove = [
    "Making barricading of excavation trenches",
    "Laying Cost of M.S pipe",
]

In [116]:
rates_to_remove = [929.52, 1118.23, 1755.08]

In [117]:
filtered_df = final_df[
    ~final_df['Item Description'].astype(str).str.startswith(tuple(descriptions_to_remove)) &
    ~final_df['estimate rate'].isin(rates_to_remove)
]

In [121]:
filtered_df.head(30)

,Item Description,class,DIA,estimate rate,Units
2,Carrying CI/DI pipes with specials and valves ...,DI,150,112.00,Mtr.
3,200 mm dia Pipe,DI,200,136.00,Mtr.
4,250 mm dia Pipe,DI,250,164.00,Mtr.
5,300 mm dia Pipe,DI,300,192.00,Mtr.
6,"Filling the pipe line with water, testing hydr...",DI,150,4.20,Mtr.
7,200 mm dia Pipe,DI,200,5.61,Mtr.
8,250 mm dia Pipe,DI,250,6.66,Mtr.
9,300 mm dia Pipe,DI,300,7.22,Mtr.
10,Cleaning thoroughly the inner surface of pipe ...,DI,150,1.54,Mtr.
11,200 mm dia Pipe,DI,200,2.38,Mtr.
12,250 mm dia Pipe,DI,250,3.47,Mtr.
13,300 mm dia Pipe,DI,300,4.80,Mtr.
43,Submission of complete detailed drawing of dis...,DI,,0.38,Mtr.
55,Supply & Delivery (at Site) of DI K-9 Pipes co...,K9,150,2161.00,Mtr.
56,200 mm dia Pipe,DI,200,2881.00,Mtr.
57,250 mm dia Pipe,DI,250,3857.00,Mtr.
58,300 mm dia Pipe,DI,300,4887.00,Mtr.
59,Supply of M.S pipe Including Coating including...,M.S,150,2505.19,Mtr.
60,200 mm dia Pipe,DI,200,3812.56,Mtr.
61,250 mm dia Pipe,DI,250,4398.50,Mtr.
62,300 mm dia Pipe,DI,300,5714.49,Mtr.

In [134]:
phrases_to_remove = [
    "Filling the pipe",
    "Cleaning thoroughly",
    "Submission of complete detailed drawing",
    "Making barricading of excavation trenches of r...",
    "Laying Cost of M.S pipe \n150 mm dia Pipe",
    "Laying Cost of M.S pipe \n150 mm dia Pipe",
]

In [135]:
filtered_df = final_df[
    ~final_df['Item Description'].astype(str).str.startswith(tuple(phrases_to_remove)) &
    ~final_df['estimate rate'].isin(rates_to_remove)
]

In [136]:
filtered_df.head(30)

,Item Description,class,DIA,estimate rate,Units
2,Carrying CI/DI pipes with specials and valves ...,DI,150,112.00,Mtr.
3,200 mm dia Pipe,DI,200,136.00,Mtr.
4,250 mm dia Pipe,DI,250,164.00,Mtr.
5,300 mm dia Pipe,DI,300,192.00,Mtr.
44,Making barricading of excavation trenches of r...,DI,75,118.00,Mtr.
49,Laying Cost of M.S pipe \n150 mm dia Pipe,M.S,150,564.38,Mtr.
50,200 mm dia Pipe,DI,200,929.52,Mtr.
51,250 mm dia Pipe,DI,250,1118.23,Mtr.
52,300 mm dia Pipe,DI,300,1755.08,Mtr.
55,Supply & Delivery (at Site) of DI K-9 Pipes co...,K9,150,2161.00,Mtr.
56,200 mm dia Pipe,DI,200,2881.00,Mtr.
57,250 mm dia Pipe,DI,250,3857.00,Mtr.
58,300 mm dia Pipe,DI,300,4887.00,Mtr.
59,Supply of M.S pipe Including Coating including...,M.S,150,2505.19,Mtr.
60,200 mm dia Pipe,DI,200,3812.56,Mtr.
61,250 mm dia Pipe,DI,250,4398.50,Mtr.
62,300 mm dia Pipe,DI,300,5714.49,Mtr.

In [137]:
phrases_to_remove = [
    "Filling the pipe",
    "Cleaning thoroughly",
    "Submission of complete detailed drawing",
    "Making barricading of excavation trenches",
    "Laying Cost of M.S pipe"
]

In [140]:
rates_to_remove = [4.20, 5.61, 6.66, 7.22, 2.38, 3.47, 4.80, 1.54, 0.38, 564.38, 929.52, 1118.23, 1755.08, 118.00]

filtered_df = final_df[
    ~final_df['Item Description'].astype(str).str.startswith(tuple(phrases_to_remove)) &
    ~final_df['estimate rate'].isin(rates_to_remove)
]

In [141]:
filtered_df.head(30)

,Item Description,class,DIA,estimate rate,Units
2,Carrying CI/DI pipes with specials and valves ...,DI,150,112.00,Mtr.
3,200 mm dia Pipe,DI,200,136.00,Mtr.
4,250 mm dia Pipe,DI,250,164.00,Mtr.
5,300 mm dia Pipe,DI,300,192.00,Mtr.
55,Supply & Delivery (at Site) of DI K-9 Pipes co...,K9,150,2161.00,Mtr.
56,200 mm dia Pipe,DI,200,2881.00,Mtr.
57,250 mm dia Pipe,DI,250,3857.00,Mtr.
58,300 mm dia Pipe,DI,300,4887.00,Mtr.
59,Supply of M.S pipe Including Coating including...,M.S,150,2505.19,Mtr.
60,200 mm dia Pipe,DI,200,3812.56,Mtr.
61,250 mm dia Pipe,DI,250,4398.50,Mtr.
62,300 mm dia Pipe,DI,300,5714.49,Mtr.