In [1]:
import pandas as pd

# Load the Excel file
file_path = "all_data.xlsx"  # Update path if needed
df = pd.read_excel(file_path, sheet_name="Sheet1")

# Function to extract pipe class/type
def extract_class(text):
    text = str(text).lower()
    if 'k-7' in text:
        return 'K-7'
    elif 'k-9' in text or 'k9' in text:
        return 'K-9'
    elif 'm.s' in text or 'ms' in text:
        return 'M.S'
    elif 'hdpe' in text:
        return 'HDPE'
    elif 'upvc' in text:
        return 'UPVC'
    elif 'pvc' in text:
        return 'PVC'
    elif 'ci' in text:
        return 'CI'
    elif 'di' in text:
        return 'DI'
    else:
        return None

# Filter rows where 'Tender Brief' contains 'pipe' (case-insensitive)
pipe_df = df[df['Tender Brief'].str.contains('pipe', case=False, na=False)].copy()

# Apply the class extraction function
pipe_df['Pipe Class'] = pipe_df['Tender Brief'].apply(extract_class)

# Display the result
pipe_df.head()

,TDR,Tendering Authority,Tender Brief,DocumentFees,EMD,Tender Amount,Location,State,DueDate,TenderNo,Address,ContactEmail,TenderId,pubDate,Pipe Class
0,49110083,Public Health Engineer Organisation,Laying Of Di Pipe From Bhainsa To Wtp In Conne...,10000,651359.0,65135891,patnagarh,Odisha,2025-05-28,ACEPHBGR 02/2025-26,"Additional Chief Engineer, PH Division, Balangir",NaN,2025_PHEO_113334_1,2025-05-13,CI
1,48706761,Kerala Water Authority,AMRUT-2.0 - CHERPULASSERI-Gap filling and Extr...,2760,50000.0,3448454,Palakkad,Kerala,2025-04-21,03/25-26/EE/WSP/PKD,WSP division Palakkad,NaN,2025_KWA_759976_1,2025-04-15,PVC
2,48662494,Urban Local Bodies,Supplying And Laying Of Di Pipe And Ms Pipe Fo...,0,150000.0,0,asansol,West Bengal,2025-05-05,EQ-02 /WS/AMRUT/ENG/2025-26,Asansol Municipal Corporation,NaN,2025_MAD_835433_1,2025-04-11,M.S
3,47886304,Public Health Engineer Organisation,Laying Of Di Pipe From Intake To Dedgaon And C...,10000,1010000.0,100995000,kantabanji,Odisha,2025-03-17,EICPH-06/2024-25 Dtd.14.02.2025,"Office of the Engineer-in-Chief (PH), Odisha, ...",NaN,2025_PHEO_111048_1,2025-02-21,CI
4,47606940,Municipal Affairs Department,"Surveying, Soil Investigation, Planning, Desig...",0,639282.0,31964076,alipurduar,West Bengal,2025-03-10,"25 of SE(N)/MED/2024-25, dated-06.02.2025",OFFICE OF THE SUPERINTENDING ENGINEER (NORTH C...,NaN,2025_MAD_812211_1,2025-03-03,M.S

In [2]:
import pandas as pd

# Load the Excel file
file_path = "all_data.xlsx"  # Update path as needed
df = pd.read_excel(file_path, sheet_name="Sheet1")

# Function to extract pipe class/type
def extract_class(text):
    text = str(text).lower()
    if 'k-7' in text:
        return 'K-7'
    elif 'k-9' in text or 'k9' in text:
        return 'K-9'
    elif 'm.s' in text or 'ms' in text:
        return 'M.S'
    elif 'hdpe' in text:
        return 'HDPE'
    elif 'upvc' in text:
        return 'UPVC'
    elif 'pvc' in text:
        return 'PVC'
    elif 'ci' in text:
        return 'CI'
    elif 'di' in text:
        return 'DI'
    else:
        return None

# Function to extract unit
def extract_unit(text):
    text = str(text).lower()
    if 'mtr' in text or 'meter' in text:
        return 'Mtr'
    elif 'each' in text:
        return 'Each'
    elif 'kg' in text:
        return 'Kg'
    elif 'litre' in text or 'ltr' in text:
        return 'Litre'
    elif 'set' in text:
        return 'Set'
    elif 'nos' in text or 'no.' in text:
        return 'Nos'
    else:
        return None

# Filter rows where 'Tender Brief' contains 'pipe'
pipe_df = df[df['Tender Brief'].str.contains('pipe', case=False, na=False)].copy()

# Apply the class and unit extraction functions
pipe_df['Pipe Class'] = pipe_df['Tender Brief'].apply(extract_class)
pipe_df['Unit'] = pipe_df['Tender Brief'].apply(extract_unit)

# Display the first few results
pipe_df.head()

,TDR,Tendering Authority,Tender Brief,DocumentFees,EMD,Tender Amount,Location,State,DueDate,TenderNo,Address,ContactEmail,TenderId,pubDate,Pipe Class,Unit
0,49110083,Public Health Engineer Organisation,Laying Of Di Pipe From Bhainsa To Wtp In Conne...,10000,651359.0,65135891,patnagarh,Odisha,2025-05-28,ACEPHBGR 02/2025-26,"Additional Chief Engineer, PH Division, Balangir",NaN,2025_PHEO_113334_1,2025-05-13,CI,None
1,48706761,Kerala Water Authority,AMRUT-2.0 - CHERPULASSERI-Gap filling and Extr...,2760,50000.0,3448454,Palakkad,Kerala,2025-04-21,03/25-26/EE/WSP/PKD,WSP division Palakkad,NaN,2025_KWA_759976_1,2025-04-15,PVC,None
2,48662494,Urban Local Bodies,Supplying And Laying Of Di Pipe And Ms Pipe Fo...,0,150000.0,0,asansol,West Bengal,2025-05-05,EQ-02 /WS/AMRUT/ENG/2025-26,Asansol Municipal Corporation,NaN,2025_MAD_835433_1,2025-04-11,M.S,None
3,47886304,Public Health Engineer Organisation,Laying Of Di Pipe From Intake To Dedgaon And C...,10000,1010000.0,100995000,kantabanji,Odisha,2025-03-17,EICPH-06/2024-25 Dtd.14.02.2025,"Office of the Engineer-in-Chief (PH), Odisha, ...",NaN,2025_PHEO_111048_1,2025-02-21,CI,None
4,47606940,Municipal Affairs Department,"Surveying, Soil Investigation, Planning, Desig...",0,639282.0,31964076,alipurduar,West Bengal,2025-03-10,"25 of SE(N)/MED/2024-25, dated-06.02.2025",OFFICE OF THE SUPERINTENDING ENGINEER (NORTH C...,NaN,2025_MAD_812211_1,2025-03-03,M.S,None

In [5]:
pipe_df

,TDR,Tendering Authority,Tender Brief,DocumentFees,EMD,Tender Amount,Location,State,DueDate,TenderNo,Address,ContactEmail,TenderId,pubDate,Pipe Class,Unit
0,49110083,Public Health Engineer Organisation,Laying Of Di Pipe From Bhainsa To Wtp In Conne...,10000,651359.0,65135891,patnagarh,Odisha,2025-05-28,ACEPHBGR 02/2025-26,"Additional Chief Engineer, PH Division, Balangir",NaN,2025_PHEO_113334_1,2025-05-13,CI,None
1,48706761,Kerala Water Authority,AMRUT-2.0 - CHERPULASSERI-Gap filling and Extr...,2760,50000.0,3448454,Palakkad,Kerala,2025-04-21,03/25-26/EE/WSP/PKD,WSP division Palakkad,NaN,2025_KWA_759976_1,2025-04-15,PVC,None
2,48662494,Urban Local Bodies,Supplying And Laying Of Di Pipe And Ms Pipe Fo...,0,150000.0,0,asansol,West Bengal,2025-05-05,EQ-02 /WS/AMRUT/ENG/2025-26,Asansol Municipal Corporation,NaN,2025_MAD_835433_1,2025-04-11,M.S,None
3,47886304,Public Health Engineer Organisation,Laying Of Di Pipe From Intake To Dedgaon And C...,10000,1010000.0,100995000,kantabanji,Odisha,2025-03-17,EICPH-06/2024-25 Dtd.14.02.2025,"Office of the Engineer-in-Chief (PH), Odisha, ...",NaN,2025_PHEO_111048_1,2025-02-21,CI,None
4,47606940,Municipal Affairs Department,"Surveying, Soil Investigation, Planning, Desig...",0,639282.0,31964076,alipurduar,West Bengal,2025-03-10,"25 of SE(N)/MED/2024-25, dated-06.02.2025",OFFICE OF THE SUPERINTENDING ENGINEER (NORTH C...,NaN,2025_MAD_812211_1,2025-03-03,M.S,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67134,49409156,Municipalities,Drilling Of Bore Well And Supply Delivery And ...,0,3780.0,378027,TIRUPATHI,Andhra Pradesh,2025-06-16,"20 / PTR / General Fund / 2025 - 2026, Dated: ...","MUNICIPAL OFFICE, PUTTUR",putturmc@yahoo.com,815790,2025-05-30,None,None
67136,49409153,Municipalities,Drilling Of Bore Well And Supply Delivery And ...,0,2940.0,294049,TIRUPATHI,Andhra Pradesh,2025-06-16,"15 / PTR / General Fund / 2025 - 2026, Dated: ...","MUNICIPAL OFFICE, PUTTUR",putturmc@yahoo.com,815953,2025-05-30,None,None
67137,49409152,Municipalities,Drilling Of Bore Well And Supply Delivery And ...,0,3948.0,394807,TIRUPATHI,Andhra Pradesh,2025-06-16,"17 / PTR / General Fund / 2025 - 2026, Dated: ...","MUNICIPAL OFFICE, PUTTUR",putturmc@yahoo.com,815975,2025-05-30,None,None
67138,49409151,Municipalities,Laying Of 90Mm Dia Pipeline From Nandhimangala...,0,4199.0,419858,TIRUPATHI,Andhra Pradesh,2025-06-16,"18 / PTR / General Fund / 2025 - 2026, Dated: ...","MUNICIPAL OFFICE, PUTTUR",putturmc@yahoo.com,815986,2025-05-30,CI,None
67139,49409150,Municipalities,Laying Of 90Mm Dia Pipeline From Vinayaka Temp...,0,4171.0,417126,TIRUPATHI,Andhra Pradesh,2025-06-16,"19 / PTR / General Fund / 2025 - 2026, Dated: ...","MUNICIPAL OFFICE, PUTTUR",putturmc@yahoo.com,816046,2025-05-30,CI,Nos

In [4]:
pipe_df.shape

(4512, 16)

In [6]:
import pandas as pd

# Load the Excel file
file_path = "all_data.xlsx"
df = pd.read_excel(file_path, sheet_name="Sheet1")

# Function to extract pipe class/type
def extract_class(text):
    text = str(text).lower()
    if 'k-7' in text:
        return 'K-7'
    elif 'k-9' in text or 'k9' in text:
        return 'K-9'
    elif 'm.s' in text or 'ms' in text:
        return 'M.S'
    elif 'hdpe' in text:
        return 'HDPE'
    elif 'upvc' in text:
        return 'UPVC'
    elif 'pvc' in text:
        return 'PVC'
    elif 'ci' in text:
        return 'CI'
    elif 'di' in text:
        return 'DI'
    else:
        return None

# Function to extract unit
def extract_unit(text):
    text = str(text).lower()
    if 'mtr' in text or 'meter' in text:
        return 'Mtr'
    elif 'each' in text:
        return 'Each'
    elif 'kg' in text:
        return 'Kg'
    elif 'litre' in text or 'ltr' in text:
        return 'Litre'
    elif 'set' in text:
        return 'Set'
    elif 'nos' in text or 'no.' in text:
        return 'Nos'
    else:
        return None

# Apply to full DataFrame, not filtered by "pipe"
df['Pipe Class'] = df['Tender Brief'].apply(extract_class)
df['Unit'] = df['Tender Brief'].apply(extract_unit)

# Filter rows where either Pipe Class or Unit was found
pipe_df = df[df['Pipe Class'].notnull() | df['Unit'].notnull()]

# Show shape and sample
print(pipe_df.shape)
pipe_df.head()

(41965, 16)

,TDR,Tendering Authority,Tender Brief,DocumentFees,EMD,Tender Amount,Location,State,DueDate,TenderNo,Address,ContactEmail,TenderId,pubDate,Pipe Class,Unit
0,49110083,Public Health Engineer Organisation,Laying Of Di Pipe From Bhainsa To Wtp In Conne...,10000,651359.0,65135891,patnagarh,Odisha,2025-05-28,ACEPHBGR 02/2025-26,"Additional Chief Engineer, PH Division, Balangir",NaN,2025_PHEO_113334_1,2025-05-13,CI,None
1,48706761,Kerala Water Authority,AMRUT-2.0 - CHERPULASSERI-Gap filling and Extr...,2760,50000.0,3448454,Palakkad,Kerala,2025-04-21,03/25-26/EE/WSP/PKD,WSP division Palakkad,NaN,2025_KWA_759976_1,2025-04-15,PVC,None
2,48662494,Urban Local Bodies,Supplying And Laying Of Di Pipe And Ms Pipe Fo...,0,150000.0,0,asansol,West Bengal,2025-05-05,EQ-02 /WS/AMRUT/ENG/2025-26,Asansol Municipal Corporation,NaN,2025_MAD_835433_1,2025-04-11,M.S,None
3,47886304,Public Health Engineer Organisation,Laying Of Di Pipe From Intake To Dedgaon And C...,10000,1010000.0,100995000,kantabanji,Odisha,2025-03-17,EICPH-06/2024-25 Dtd.14.02.2025,"Office of the Engineer-in-Chief (PH), Odisha, ...",NaN,2025_PHEO_111048_1,2025-02-21,CI,None
4,47606940,Municipal Affairs Department,"Surveying, Soil Investigation, Planning, Desig...",0,639282.0,31964076,alipurduar,West Bengal,2025-03-10,"25 of SE(N)/MED/2024-25, dated-06.02.2025",OFFICE OF THE SUPERINTENDING ENGINEER (NORTH C...,NaN,2025_MAD_812211_1,2025-03-03,M.S,None

In [7]:
pipe_df.to_excel("tenders_with_class_or_unit.xlsx", index=False)