In [2]:
pip install pandas openpyxl xlrd

Requirement already satisfied: pandas in c:\users\jaydeb\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\jaydeb\anaconda3\lib\site-packages (3.1.5)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jaydeb\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaydeb\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jaydeb\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jaydeb\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\jaydeb\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\jaydeb\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import re
import numpy as np

df = pd.read_excel("BOQ_1833226.xls", skiprows=10)


description_column = next((col for col in df.columns if isinstance(col, str) and "description" in col.lower()), None)
qty_column = next((col for col in df.columns if isinstance(col, str) and "qty" in col.lower()), None)
unit_column = next((col for col in df.columns if isinstance(col, str) and "unit" in col.lower()), None)
rate_column = next((col for col in df.columns if isinstance(col, str) and "rate" in col.lower()), None)
amount_column = next((col for col in df.columns if isinstance(col, str) and "amount" in col.lower()), None)

if not description_column:
    raise Exception("Could not find 'Item Description' column.")

class_pattern = r"\b(DI|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"

name_of_work = str(df.iloc[0][description_column])[:80]

results = []

for _, row in df.iterrows():
    text = str(row.get(description_column, "")).strip()

    if len(text) < 5 or text.lower() in ["nan", ""]:
        continue

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)

    dia_values = [m[0] for m in dia_match]
    class_values = list(set(class_match))

    def safe_number(val):
        try:
            return float(val) if pd.notna(val) else None
        except:
            return None

    unit_val = str(row.get(unit_column, "")).strip() if unit_column else ""
    rate_val = safe_number(row.get(rate_column, "")) if rate_column else None
    amount_val = safe_number(row.get(amount_column, "")) if amount_column else None
    qty_val = safe_number(row.get(qty_column, "")) if qty_column else None

    if qty_val in [None, "", 0] and rate_val and amount_val:
        try:
            qty_val = round(amount_val / rate_val, 2)
        except ZeroDivisionError:
            qty_val = ""

    result = {
        "tender_details_id": "BOQ_1833226",
        "name_of_work": name_of_work,
        "item_description": text[:150],
        "class": ",".join(class_values),
        "DIA": ",".join(set(dia_values)),
        "unit": unit_val,
        "quantity": qty_val,
        "estimate rate": rate_val,
        "total amount with taxes": amount_val
    }

    if result["class"] or result["DIA"] or result["quantity"]:
        results.append(result)
final_df = pd.DataFrame(results)
final_df.replace({np.nan: ""}, inplace=True)

output_path = "boq_final_with_quantity.xlsx"
final_df.to_excel(output_path, index=False)

print(f" File saved: {output_path}")
final_df.head()

 File saved: boq_final_with_quantity.xlsx

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
final_df.head()

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0

In [6]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
5,BOQ_1833226,2,"Filling the pipe line with water, testing hydr...",,"150,10,00,3114,1965",Mtr.,4955.0,4.2,20811.0
6,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,5.61,19382.55
7,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,6.66,13719.6
8,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,7.22,1949.4
9,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,4955.0,1.54,7630.7
10,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,2.38,8222.9
11,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,3.47,7148.2
12,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,4.8,1296.0
13,BOQ_1833226,2,Cutting DI pipe (all class & type) to required...,DI,"150,200",Each,84.0,141.0,11844.0
14,BOQ_1833226,2,c) 250mm.dia.to 350mm.dia pipe,,"350,250",Each,23.0,263.0,6049.0
15,BOQ_1833226,2,Chamfering the spigot end of all type/class of...,DI,150,Each,100.0,108.0,10800.0
16,BOQ_1833226,2,200 mm dia Pipe,,200,Each,70.0,113.0,7910.0
17,BOQ_1833226,2,250 mm dia Pipe,,250,Each,42.0,120.0,5040.0
18,BOQ_1833226,2,300 mm dia Pipe,,300,Each,6.0,160.0,960.0
19,BOQ_1833226,2,"Making flange joint to DI/CI pipes, specials a...","DI,CI",150,Each,20.0,220.0,4400.0
20,BOQ_1833226,2,200 mm dia Pipe,,200,Each,14.0,237.0,3318.0
21,BOQ_1833226,2,250 mm dia Pipe,,250,Each,8.0,329.0,2632.0
22,BOQ_1833226,2,300 mm dia Pipe,,300,Each,2.0,351.0,702.0
23,BOQ_1833226,2,All Types of D.I Ductile Iron (D.I) specials (...,,"150,300,2000,9523,25",Kg,6202.5,128.0,793920.0
24,BOQ_1833226,2,"b) Double socketed bend, 150 mm dia. to 300 mm...",,"150,300",Kg,5770.5,125.0,721312.5
25,BOQ_1833226,2,"c) Tail piece, 150 mm dia. to 300 mm. dia.",,"150,300",Kg,6533.4,144.0,940809.6
26,BOQ_1833226,2,Cast iron kinetic double orifice type air rele...,,"10,1538,80",Each,2.0,15691.0,31382.0
27,BOQ_1833226,2,Cost iron double flanged manually operated slu...,,"150,1538,1993,2000,410",Each,10.0,7487.0,74870.0
28,BOQ_1833226,2,200 mm dia,,200,Each,7.0,14769.0,103383.0
29,BOQ_1833226,2,250 mm dia,,250,Each,4.0,20429.0,81716.0
30,BOQ_1833226,2,300 mm dia,,300,Each,1.0,24205.0,24205.0
31,BOQ_1833226,2,"Supplying, fitting and fixing air valve splash...",MS,24,Each,2.0,4224.0,8448.0
32,BOQ_1833226,2,Cast iron double flanged single door swing Non...,,"300,24,10,16,5312,200,350,210,15,318",Each,1.0,54522.0,54522.0
33,BOQ_1833226,2,250 mm dia,,250,Each,1.0,37693.0,37693.0
34,BOQ_1833226,2,200 mm dia,,200,Each,3.0,26883.0,80649.0
35,BOQ_1833226,2,Construction of different dia Sluice valve /Ai...,,"150,100,80",Each,10.0,11990.0,119900.0
36,BOQ_1833226,2,ii) 200 mm dia pipe,,200,Each,10.0,15194.0,151940.0
37,BOQ_1833226,2,iii) 250 mm to350 mm dia pipe,,250,Each,7.0,18881.0,132167.0
38,BOQ_1833226,2,"Construction of Thrust Block, 300 mm dia Pipe",,300,Each,6.0,4952.34,29714.04
39,BOQ_1833226,2,Bituminous pucca road (approx. 450mm depth) cu...,,"150,250,2004,3114,450",Cum,317.83,1023.0,325140.09
40,BOQ_1833226,2,Dismantling all type of plain cement concrete ...,,"150,7634,2012",Cum,300.55,939.0,282216.45
41,BOQ_1833226,2,"Removal of rubbish, earth etc. From the workin...",,,Cum,618.38,166.0,102651.08
42,BOQ_1833226,2,Submission of complete detailed drawing of dis...,,,Mtr.,10740.0,0.38,4081.2
43,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
44,BOQ_1833226,2,Ordinary Cement concrete (mix 1:1.5:3) with gr...,,20,Cum,3.02,5858.53,17692.76
45,BOQ_1833226,2,Hire and labour charges for shuttering with ce...,,"25,30",sqm,24.17,205.0,4954.85
46,BOQ_1833226,2,Reinforcement for reinforced concrete work in ...,,16,MT,0.24,61751.16,14820.28
47,BOQ_1833226,2,Brick work with 1st class bricks in cement mor...,,,Cum,4.03,4919.86,19827.04
48,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
49,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
50,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
51,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
52,BOQ_1833226,2,Add GST of above @ 18%,,18,LS,1.0,1042633.43,1042633.43
53,BOQ_1833226,2,Supply of DI and MS Pipe With GST,"MS,DI",,nan,,,
54,BOQ_1833226,2,Supply & Delivery (at Site) of DI K-9 Pipes co...,DI,"150,2000,8329,18",Mtr.,4905.0,2161.0,10599705.0
55,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
56,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
57,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
58,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
59,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
60,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
61,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23
62,BOQ_1833226,2,Add labour welfare cess @ 1%,,,LS,1.0,368242.74,368242.74

In [7]:
output_path = "boq_final_with_quantity.xlsx"
final_df.to_excel(output_path, index=False)

In [8]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
5,BOQ_1833226,2,"Filling the pipe line with water, testing hydr...",,"150,10,00,3114,1965",Mtr.,4955.0,4.2,20811.0
6,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,5.61,19382.55
7,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,6.66,13719.6
8,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,7.22,1949.4
9,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,4955.0,1.54,7630.7
10,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,2.38,8222.9
11,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,3.47,7148.2
12,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,4.8,1296.0
13,BOQ_1833226,2,Cutting DI pipe (all class & type) to required...,DI,"150,200",Each,84.0,141.0,11844.0
14,BOQ_1833226,2,c) 250mm.dia.to 350mm.dia pipe,,"350,250",Each,23.0,263.0,6049.0
15,BOQ_1833226,2,Chamfering the spigot end of all type/class of...,DI,150,Each,100.0,108.0,10800.0
16,BOQ_1833226,2,200 mm dia Pipe,,200,Each,70.0,113.0,7910.0
17,BOQ_1833226,2,250 mm dia Pipe,,250,Each,42.0,120.0,5040.0
18,BOQ_1833226,2,300 mm dia Pipe,,300,Each,6.0,160.0,960.0
19,BOQ_1833226,2,"Making flange joint to DI/CI pipes, specials a...","DI,CI",150,Each,20.0,220.0,4400.0
20,BOQ_1833226,2,200 mm dia Pipe,,200,Each,14.0,237.0,3318.0
21,BOQ_1833226,2,250 mm dia Pipe,,250,Each,8.0,329.0,2632.0
22,BOQ_1833226,2,300 mm dia Pipe,,300,Each,2.0,351.0,702.0
23,BOQ_1833226,2,All Types of D.I Ductile Iron (D.I) specials (...,,"150,300,2000,9523,25",Kg,6202.5,128.0,793920.0
24,BOQ_1833226,2,"b) Double socketed bend, 150 mm dia. to 300 mm...",,"150,300",Kg,5770.5,125.0,721312.5
25,BOQ_1833226,2,"c) Tail piece, 150 mm dia. to 300 mm. dia.",,"150,300",Kg,6533.4,144.0,940809.6
26,BOQ_1833226,2,Cast iron kinetic double orifice type air rele...,,"10,1538,80",Each,2.0,15691.0,31382.0
27,BOQ_1833226,2,Cost iron double flanged manually operated slu...,,"150,1538,1993,2000,410",Each,10.0,7487.0,74870.0
28,BOQ_1833226,2,200 mm dia,,200,Each,7.0,14769.0,103383.0
29,BOQ_1833226,2,250 mm dia,,250,Each,4.0,20429.0,81716.0
30,BOQ_1833226,2,300 mm dia,,300,Each,1.0,24205.0,24205.0
31,BOQ_1833226,2,"Supplying, fitting and fixing air valve splash...",MS,24,Each,2.0,4224.0,8448.0
32,BOQ_1833226,2,Cast iron double flanged single door swing Non...,,"300,24,10,16,5312,200,350,210,15,318",Each,1.0,54522.0,54522.0
33,BOQ_1833226,2,250 mm dia,,250,Each,1.0,37693.0,37693.0
34,BOQ_1833226,2,200 mm dia,,200,Each,3.0,26883.0,80649.0
35,BOQ_1833226,2,Construction of different dia Sluice valve /Ai...,,"150,100,80",Each,10.0,11990.0,119900.0
36,BOQ_1833226,2,ii) 200 mm dia pipe,,200,Each,10.0,15194.0,151940.0
37,BOQ_1833226,2,iii) 250 mm to350 mm dia pipe,,250,Each,7.0,18881.0,132167.0
38,BOQ_1833226,2,"Construction of Thrust Block, 300 mm dia Pipe",,300,Each,6.0,4952.34,29714.04
39,BOQ_1833226,2,Bituminous pucca road (approx. 450mm depth) cu...,,"150,250,2004,3114,450",Cum,317.83,1023.0,325140.09
40,BOQ_1833226,2,Dismantling all type of plain cement concrete ...,,"150,7634,2012",Cum,300.55,939.0,282216.45
41,BOQ_1833226,2,"Removal of rubbish, earth etc. From the workin...",,,Cum,618.38,166.0,102651.08
42,BOQ_1833226,2,Submission of complete detailed drawing of dis...,,,Mtr.,10740.0,0.38,4081.2
43,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
44,BOQ_1833226,2,Ordinary Cement concrete (mix 1:1.5:3) with gr...,,20,Cum,3.02,5858.53,17692.76
45,BOQ_1833226,2,Hire and labour charges for shuttering with ce...,,"25,30",sqm,24.17,205.0,4954.85
46,BOQ_1833226,2,Reinforcement for reinforced concrete work in ...,,16,MT,0.24,61751.16,14820.28
47,BOQ_1833226,2,Brick work with 1st class bricks in cement mor...,,,Cum,4.03,4919.86,19827.04
48,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
49,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
50,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
51,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
52,BOQ_1833226,2,Add GST of above @ 18%,,18,LS,1.0,1042633.43,1042633.43
53,BOQ_1833226,2,Supply of DI and MS Pipe With GST,"MS,DI",,nan,,,
54,BOQ_1833226,2,Supply & Delivery (at Site) of DI K-9 Pipes co...,DI,"150,2000,8329,18",Mtr.,4905.0,2161.0,10599705.0
55,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
56,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
57,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
58,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
59,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
60,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
61,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23
62,BOQ_1833226,2,Add labour welfare cess @ 1%,,,LS,1.0,368242.74,368242.74

In [9]:
def is_valid_dia(val):
    if pd.isna(val):
        return True
    parts = str(val).split(',')
    return all(p.strip().isdigit() for p in parts) and len(parts) <= 3

final_df = final_df[final_df["DIA"].apply(is_valid_dia)]

In [10]:
unwanted_units = ["Each", "Kg", "Cum","sqm","MT","LS"]
final_df = final_df[final_df["unit"].notna()]
final_df = final_df[~final_df["unit"].isin(unwanted_units)]

final_df.reset_index(drop=True, inplace=True)

In [11]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
1,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
2,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
3,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
4,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,5.61,19382.55
5,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,6.66,13719.6
6,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,7.22,1949.4
7,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,4955.0,1.54,7630.7
8,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,2.38,8222.9
9,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,3.47,7148.2
10,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,4.8,1296.0
11,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
12,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
13,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
14,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
15,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
16,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
17,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
18,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
19,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
20,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
21,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
22,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23

In [12]:
final_df = final_df[final_df["estimate rate"] >= 100]

final_df.reset_index(drop=True, inplace=True)

In [13]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
1,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
2,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
3,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
4,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
5,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
6,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
7,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
8,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
9,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
10,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
11,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
12,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
13,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
14,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
15,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23

In [14]:
final_df = final_df.drop(columns=['name_of_work'])

In [15]:
final_df

,tender_details_id,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,Carrying CI/DI pipes with specials and valves ...,"DI,CI",150,Mtr.,4905.0,112.0,549360.0
1,BOQ_1833226,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
2,BOQ_1833226,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
3,BOQ_1833226,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
4,BOQ_1833226,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
5,BOQ_1833226,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
6,BOQ_1833226,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
7,BOQ_1833226,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
8,BOQ_1833226,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
9,BOQ_1833226,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
10,BOQ_1833226,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
11,BOQ_1833226,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
12,BOQ_1833226,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
13,BOQ_1833226,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
14,BOQ_1833226,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
15,BOQ_1833226,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23

In [16]:
def classify_pipe_type(text):
    text = text.lower()
    if "ms" in text:
        return "MS Pipe"
    elif "ci" in text or "di" in text:
        return "CI/DI Pipe"
    elif "k9" in text:
        return "K9 Pipe"
    elif "k7" in text:
        return "K7 Pipe"
    elif "supply" in text or "demand" in text:
        return "Supply & Demand"
    else:
        return "Other"

In [17]:
final_df['class'] = final_df['class'].apply(classify_pipe_type)

In [18]:
final_df_simple = final_df[['tender_details_id', 'class', 'DIA', 'estimate rate']]

In [19]:
final_df_simple.to_excel("boq_simplified_output.xlsx", index=False)

In [42]:
final_df_simple.head(10)

  tender_details_id       class  DIA estimate rate
0       BOQ_1833226  CI/DI Pipe  150         112.0
1       BOQ_1833226       Other  200         136.0
2       BOQ_1833226       Other  250         164.0
3       BOQ_1833226       Other  300         192.0
4       BOQ_1833226       Other   75         118.0
5       BOQ_1833226       Other  150        564.38
6       BOQ_1833226       Other  200        929.52
7       BOQ_1833226       Other  250       1118.23
8       BOQ_1833226       Other  300       1755.08
9       BOQ_1833226       Other  200        2881.0

In [21]:
final_output = final_df[['tender_details_id', 'class', 'DIA', 'unit', 'estimate rate']]

In [41]:
print(final_output.head(20))

   tender_details_id       class     DIA  unit  estimate rate
0        BOQ_1833226  CI/DI Pipe     150  Mtr.         112.00
1        BOQ_1833226       Other     200  Mtr.         136.00
2        BOQ_1833226       Other     250  Mtr.         164.00
3        BOQ_1833226       Other     300  Mtr.         192.00
4        BOQ_1833226       Other      75  Mtr.         118.00
5        BOQ_1833226       Other     150  Mtr.         564.38
6        BOQ_1833226       Other     200  Mtr.         929.52
7        BOQ_1833226       Other     250  Mtr.        1118.23
8        BOQ_1833226       Other     300  Mtr.        1755.08
9        BOQ_1833226       Other     200  Mtr.        2881.00
10       BOQ_1833226       Other     250  Mtr.        3857.00
11       BOQ_1833226       Other     300  Mtr.        4887.00
12       BOQ_1833226       Other  150,18  Mtr.        2505.19
13       BOQ_1833226       Other     200  Mtr.        3812.56
14       BOQ_1833226       Other     250  Mtr.        4398.50
15       BOQ_1833226       Other     300  Mtr.        5714.49

In [25]:
df.columns = df.columns.str.strip()

In [26]:
def detect_pipe_class(desc):
    desc = str(desc).lower()
    if "m.s" in desc or "ms pipe" in desc:
        return "M.S pipe"
    elif "di" in desc or "ci" in desc:
        return "DI,CI"
    elif "k9" in desc:
        return "K9 Pipe"
    elif "k7" in desc:
        return "K7 Pipe"
    elif "supply" in desc and "pipe" in desc:
        return "Supply pipe"
    else:
        return ""

In [30]:
df['class'] = df['Item Description'].apply(detect_pipe_class)

In [32]:
desc_col = next((col for col in df.columns if 'description' in col.lower()), None)

if desc_col:
    df['class'] = df[desc_col].apply(detect_pipe_class)
else:
    raise Exception("Could not find the item description column.")

In [37]:
df.head(5)

,Sl.\nNo.,Item Description,Item Code / Make,Quantity,Units,Estimated Rate in \nRs. P,Unnamed: 6,Unnamed: 7,Addition / Deduction,Addition / Deduction Values,...,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242,class
0,1,2,3,4.0,5,6.0,7.0,8.0,9,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,1,Cost for DI K-9 & M.S Pipes with Fittings & Va...,BI01010001010000000000000515BI0100001112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.00,Construction of chamber for 100mm sluices valve,item1,10.000,1 Nos,M.S pipe
2,1.01,Carrying CI/DI pipes with specials and valves ...,BI01010001010000000000000515BI0100001113,4905.0,Mtr.,112.0,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,1.01,"Supplying, Conveying and fixing spls. Includin...",item1,123.223,Nos,"DI,CI"
3,1.02,200 mm dia Pipe,BI01010001010000000000000515BI0100001114,3420.0,Mtr.,136.0,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,1.02,Construction of chamber for 100mm sluice plates,item2,213.000,Nos,"DI,CI"
4,1.03,250 mm dia Pipe,BI01010001010000000000000515BI0100001115,2040.0,Mtr.,164.0,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,1.02,Construction of chamber for 100mm sluice plates,item2,213.000,Nos,"DI,CI"