In [1]:
pip install pandas openpyxl xlrd

Requirement already satisfied: pandas in c:\users\rashmi\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\rashmi\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: xlrd in c:\users\rashmi\anaconda3\lib\site-packages (2.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rashmi\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rashmi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rashmi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rashmi\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\rashmi\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\rashmi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
file_path = 'BOQ_1833226.xls' 
sheet_name = 'BoQ1'

In [3]:
df = pd.read_excel("BOQ_1833226.xls")

In [4]:
df.head(10)

,Percentage BoQ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242
0,BoQ_Ver4.0,Percentage,Normal,INR Only,INR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Select, At Par, Excess (+), Less (-)",NaN,IOCL,Select,Excess (+),Less (-),Excess (+),Less (-),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tender Inviting Authority: SUPERINTENDING ENGI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Name of Work: Supplying and Laying Of Clear Wa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Contract No: 31/AMRUT 2.0/SE(CC)/2024-25(2nd ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Name of the Bidder/ Bidding Firm / Company :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PRICE SCHEDULE\n(This BOQ template must not be...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NUMBER #,TEXT #,TEXT #,NUMBER #,TEXT #,NUMBER,NUMBER,TEXT,TEXT #,NUMBER #,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Sl.\nNo.,Item Description,Item Code / Make,Quantity,Units,Estimated Rate in \nRs. P,NaN,NaN,Addition / Deduction,Addition / Deduction Values,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df.dropna(how='all').dropna(axis=1, how='all')

In [6]:
df

,Percentage BoQ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242
0,BoQ_Ver4.0,Percentage,Normal,INR Only,INR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Select, At Par, Excess (+), Less (-)",NaN,IOCL,Select,Excess (+),Less (-),Excess (+),Less (-),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tender Inviting Authority: SUPERINTENDING ENGI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Name of Work: Supplying and Laying Of Clear Wa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Contract No: 31/AMRUT 2.0/SE(CC)/2024-25(2nd ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,2.08,300 mm dia Pipe,BI01010001010000000000000515BI0100001173,2.5,Mtr.,5714.49,NaN,NaN,Excess(+),1,...,NaN,NaN,14286.23,14286.23,INR Fourteen Thousand Two Hundred Eighty Six &...,NaN,NaN,NaN,NaN,NaN
73,2.09,Add labour welfare cess @ 1%,BI01010001010000000000000515BI0100001174,1,LS,368242.74,NaN,NaN,Excess(+),1,...,NaN,NaN,368242.74,368242.74,INR Three Lakh Sixty Eight Thousand Two Hundre...,4.0,Construction of chamber for 100mm sluice plates,item5,10.0,Nos
74,Total in Figures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37192516.94,37192516.94,INR Three Crore Seventy One Lakh Ninety Two Th...,4.0,Construction of chamber for 100mm sluice plates,item5,10.0,Nos
75,Quoted Rate in Figures,NaN,NaN,NaN,Select,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,INR Zero Only,NaN,NaN,NaN,NaN,NaN
76,Quoted Rate in Words,NaN,INR Zero Only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
keywords = ['pipe', 'Pipe', 'Pipes']

In [8]:
df_filtered = df[df.astype(str).apply(lambda x: x.str.contains('|'.join(keywords), case=False)).any(axis=1)]

In [9]:
df_filtered.columns = [f"Col{i}" for i in range(len(df_filtered.columns))]

In [10]:
extracted_data = df_filtered[[ 'Col1', 'Col2', 'Col3', 'Col4' ]]

In [11]:
extracted_data.columns = ['Item Description', 'Estimated Rate', 'Quantity', 'Total Amount with Taxes (INR)']

In [12]:
print(extracted_data)

                                     Item Description  \
11  Cost for DI K-9 & M.S Pipes with Fittings & Va...
12  Carrying CI/DI pipes with specials and valves ...
13                                   200 mm dia  Pipe
14                                   250 mm dia  Pipe
15                                   300 mm dia  Pipe
16  Filling the pipe line with water, testing hydr...
17                                   200 mm dia  Pipe
18                                   250 mm dia  Pipe
19                                   300 mm dia  Pipe
20  Cleaning thoroughly the inner surface of pipe ...
21                                   200 mm dia  Pipe
22                                   250 mm dia  Pipe
23                                   300 mm dia  Pipe
24  Cutting DI pipe (all class & type) to required...
25                     c) 250mm.dia.to 350mm.dia pipe
26  Chamfering the spigot end of all type/class of...
27                                   200 mm dia  Pipe
28                                   250 mm dia  Pipe
29                                   300 mm dia  Pipe
30  Making flange joint to DI/CI pipes, specials a...
31                                   200 mm dia  Pipe
32                                   250 mm dia  Pipe
33                                   300 mm dia  Pipe
46  Construction of different dia Sluice valve /Ai...
47                                ii) 200 mm dia pipe
48                      iii) 250 mm to350 mm dia pipe
49     Construction of Thrust Block, 300 mm dia  Pipe
50  Bituminous pucca road (approx. 450mm depth) cu...
51  Dismantling all type of plain cement concrete ...
53  Submission of complete detailed drawing of dis...
59         Laying Cost of M.S pipe \n150 mm dia  Pipe
60                                   200 mm dia  Pipe
61                                   250 mm dia  Pipe
62                                   300 mm dia  Pipe
64                  Supply of DI and MS Pipe With GST
65  Supply & Delivery (at Site) of DI K-9 Pipes co...
66                                   200 mm dia  Pipe
67                                   250 mm dia  Pipe
68                                   300 mm dia  Pipe
69  Supply of M.S pipe Including Coating including...
70                                   200 mm dia  Pipe
71                                   250 mm dia  Pipe
72                                   300 mm dia  Pipe

                              Estimated Rate Quantity  \
11  BI01010001010000000000000515BI0100001112      NaN
12  BI01010001010000000000000515BI0100001113     4905
13  BI01010001010000000000000515BI0100001114     3420
14  BI01010001010000000000000515BI0100001115     2040
15  BI01010001010000000000000515BI0100001116    267.5
16  BI01010001010000000000000515BI0100001117     4955
17  BI01010001010000000000000515BI0100001118     3455
18  BI01010001010000000000000515BI0100001119     2060
19  BI01010001010000000000000515BI0100001120      270
20  BI01010001010000000000000515BI0100001121     4955
21  BI01010001010000000000000515BI0100001122     3455
22  BI01010001010000000000000515BI0100001123     2060
23  BI01010001010000000000000515BI0100001124      270
24  BI01010001010000000000000515BI0100001125       84
25  BI01010001010000000000000515BI0100001126       23
26  BI01010001010000000000000515BI0100001127      100
27  BI01010001010000000000000515BI0100001128       70
28  BI01010001010000000000000515BI0100001129       42
29  BI01010001010000000000000515BI0100001130        6
30  BI01010001010000000000000515BI0100001131       20
31  BI01010001010000000000000515BI0100001132       14
32  BI01010001010000000000000515BI0100001133        8
33  BI01010001010000000000000515BI0100001134        2
46  BI01010001010000000000000515BI0100001147       10
47  BI01010001010000000000000515BI0100001148       10
48  BI01010001010000000000000515BI0100001149        7
49  BI01010001010000000000000515BI0100001150        6
50  BI01010001010000000000000515BI0100001151   317.83
51  BI01010001010000000000000515BI0100001152   300.55
53  BI01010001010000000000000515BI0100001154    10740
59  BI01010001010000000000000515BI0100001160       50
60  BI01010001010000000000000515BI0100001161       35
61  BI01010001010000000000000515BI0100001162       20
62  BI01010001010000000000000515BI0100001163      2.5
64  BI01010001010000000000000515BI0100001165      NaN
65  BI01010001010000000000000515BI0100001166     4905
66  BI01010001010000000000000515BI0100001167     3420
67  BI01010001010000000000000515BI0100001168     2040
68  BI01010001010000000000000515BI0100001169    267.5
69  BI01010001010000000000000515BI0100001170       50
70  BI01010001010000000000000515BI0100001171       35
71  BI01010001010000000000000515BI0100001172       20
72  BI01010001010000000000000515BI0100001173      2.5

   Total Amount with Taxes (INR)
11                           NaN
12                          Mtr.
13                          Mtr.
14                          Mtr.
15                          Mtr.
16                          Mtr.
17                          Mtr.
18                          Mtr.
19                          Mtr.
20                          Mtr.
21                          Mtr.
22                          Mtr.
23                          Mtr.
24                          Each
25                          Each
26                          Each
27                          Each
28                          Each
29                          Each
30                          Each
31                          Each
32                          Each
33                          Each
46                          Each
47                          Each
48                          Each
49                          Each
50                           Cum
51                           Cum
53                          Mtr.
59                          Mtr.
60                          Mtr.
61                          Mtr.
62                          Mtr.
64                           NaN
65                          Mtr.
66                          Mtr.
67                          Mtr.
68                          Mtr.
69                          Mtr.
70                          Mtr.
71                          Mtr.
72                          Mtr.

In [13]:
extracted_data.to_excel('tender_data.xlsx', index=False)
print("Excel file saved as tender_data.xlsx")

Excel file saved as tender_data.xlsx

In [15]:
#######

In [16]:
import pandas as pd
import re

In [17]:
df = pd.read_excel("BOQ_1833226.xls")

In [18]:
tender_details_id = 'BOQ_1833226.xls'

In [20]:
def extract_class(description):
    classes = ['DI K-9', 'DI K9', 'DI K-7', 'DI K7', 'MS', 'PVC', 'HDPE', 'CI', 'DI PIPE', 'M.S', 'Ductile Iron']
    for c in classes:
        if c.lower() in description.lower():
            return c.upper()
    return ''

def extract_dia(description):
    match = re.search(r'(\d{2,4})\s*mm', description)
    if match:
        return int(match.group(1))
    return ''

In [23]:
result = []
for idx, row in df.iterrows():
    item_desc = str(row['Item Description'])
    class_ = extract_class(item_desc)
    dia = extract_dia(item_desc)
    length = row.get('Quantity', '')  
    ref_id = row.get('Estimated Rate', '') 
result.append({
        'Tender Details ID': tender_details_id,
        'Tender/Ref ID': ref_id,
        'Name of Work': item_desc,
        'Class': class_,
        'Diameter (mm)': dia,
        'Length': length
    })
result_df = pd.DataFrame(result)

KeyError: 'Item Description'

In [24]:
print(df.columns.tolist())

['Percentage BoQ', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129', 'Unnamed: 130', 'Unnamed: 131', 'Unnamed: 132', 'Unnamed: 133', 'Unnamed: 134', 'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'Unnamed: 138', 'Unnamed: 139', 'Unnamed: 140', 'Unnamed: 141', 'Unnamed: 142', 'Unnamed: 143', 'Unnamed: 144', 'Unnamed: 145', 'Unnamed: 146', 'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'Unnamed: 150', 'Unnamed: 151', 'Unnamed: 152', 'Unnamed: 153', 'Unnamed: 154', 'Unnamed: 155', 'Unnamed: 156', 'Unnamed: 157', 'Unnamed: 158', 'Unnamed: 159', 'Unnamed: 160', 'Unnamed: 161', 'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169', 'Unnamed: 170', 'Unnamed: 171', 'Unnamed: 172', 'Unnamed: 173', 'Unnamed: 174', 'Unnamed: 175', 'Unnamed: 176', 'Unnamed: 177', 'Unnamed: 178', 'Unnamed: 179', 'Unnamed: 180', 'Unnamed: 181', 'Unnamed: 182', 'Unnamed: 183', 'Unnamed: 184', 'Unnamed: 185', 'Unnamed: 186', 'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190', 'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194', 'Unnamed: 195', 'Unnamed: 196', 'Unnamed: 197', 'Unnamed: 198', 'Unnamed: 199', 'Unnamed: 200', 'Unnamed: 201', 'Unnamed: 202', 'Unnamed: 203', 'Unnamed: 204', 'Unnamed: 205', 'Unnamed: 206', 'Unnamed: 207', 'Unnamed: 208', 'Unnamed: 209', 'Unnamed: 210', 'Unnamed: 211', 'Unnamed: 212', 'Unnamed: 213', 'Unnamed: 214', 'Unnamed: 215', 'Unnamed: 216', 'Unnamed: 217', 'Unnamed: 218', 'Unnamed: 219', 'Unnamed: 220', 'Unnamed: 221', 'Unnamed: 222', 'Unnamed: 223', 'Unnamed: 224', 'Unnamed: 225', 'Unnamed: 226', 'Unnamed: 227', 'Unnamed: 228', 'Unnamed: 229', 'Unnamed: 230', 'Unnamed: 231', 'Unnamed: 232', 'Unnamed: 233', 'Unnamed: 234', 'Unnamed: 235', 'Unnamed: 236', 'Unnamed: 237', 'Unnamed: 238', 'Unnamed: 239', 'Unnamed: 240', 'Unnamed: 241', 'Unnamed: 242']

In [25]:
df.head(10)

,Percentage BoQ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242
0,BoQ_Ver4.0,Percentage,Normal,INR Only,INR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Select, At Par, Excess (+), Less (-)",NaN,IOCL,Select,Excess (+),Less (-),Excess (+),Less (-),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tender Inviting Authority: SUPERINTENDING ENGI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Name of Work: Supplying and Laying Of Clear Wa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Contract No: 31/AMRUT 2.0/SE(CC)/2024-25(2nd ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Name of the Bidder/ Bidding Firm / Company :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PRICE SCHEDULE\n(This BOQ template must not be...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NUMBER #,TEXT #,TEXT #,NUMBER #,TEXT #,NUMBER,NUMBER,TEXT,TEXT #,NUMBER #,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Sl.\nNo.,Item Description,Item Code / Make,Quantity,Units,Estimated Rate in \nRs. P,NaN,NaN,Addition / Deduction,Addition / Deduction Values,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
##SCOPE##

In [27]:
import pandas as pd
import xlrd
import os
import re

In [28]:
file_path = 'BOQ_1833226.xls'  
xls = pd.ExcelFile(file_path)

In [29]:
print("Available sheets:")
print(xls.sheet_names)

Available sheets:
['BoQ1', 'Macros']

In [30]:
sheet_name = [s for s in xls.sheet_names if 'error' not in s.lower()][0]
print(f"Using sheet: {sheet_name}")

Using sheet: BoQ1

In [31]:
df = pd.read_excel(file_path, sheet_name=sheet_name)

In [39]:
print("First 10 rows:")
print(df.head(10))

First 10 rows:
                                      Percentage BoQ        Unnamed: 1  \
0                                         BoQ_Ver4.0        Percentage
1               Select, At Par, Excess (+), Less (-)               NaN
2  Tender Inviting Authority: SUPERINTENDING ENGI...               NaN
3  Name of Work: Supplying and Laying Of Clear Wa...               NaN
4  Contract No:  31/AMRUT 2.0/SE(CC)/2024-25(2nd ...               NaN
5                                                                  NaN
6       Name of the Bidder/ Bidding Firm / Company :               NaN
7  PRICE SCHEDULE\n(This BOQ template must not be...               NaN
8                                           NUMBER #            TEXT #
9                                           Sl.\nNo.  Item Description

         Unnamed: 2 Unnamed: 3  Unnamed: 4                     Unnamed: 5  \
0            Normal   INR Only         INR                            NaN
1              IOCL     Select  Excess (+)                       Less (-)
2               NaN        NaN         NaN                            NaN
3               NaN        NaN         NaN                            NaN
4               NaN        NaN         NaN                            NaN
5               NaN        NaN         NaN                            NaN
6               NaN        NaN         NaN                            NaN
7               NaN        NaN         NaN                            NaN
8            TEXT #   NUMBER #      TEXT #                         NUMBER
9  Item Code / Make   Quantity       Units  Estimated Rate in \nRs.     P

   Unnamed: 6 Unnamed: 7            Unnamed: 8                   Unnamed: 9  \
0         NaN        NaN                   NaN                          NaN
1  Excess (+)   Less (-)                   NaN                          NaN
2         NaN        NaN                   NaN                          NaN
3         NaN        NaN                   NaN                          NaN
4         NaN        NaN                   NaN                          NaN
5         NaN        NaN                   NaN                          NaN
6         NaN        NaN                   NaN                          NaN
7         NaN        NaN                   NaN                          NaN
8      NUMBER       TEXT                TEXT #                     NUMBER #
9         NaN        NaN  Addition / Deduction  Addition / Deduction Values

   ... Unnamed: 233 Unnamed: 234 Unnamed: 235 Unnamed: 236 Unnamed: 237  \
0  ...          NaN          NaN          NaN          NaN          NaN
1  ...          NaN          NaN          NaN          NaN          NaN
2  ...          NaN          NaN          NaN          NaN          NaN
3  ...          NaN          NaN          NaN          NaN          NaN
4  ...          NaN          NaN          NaN          NaN          NaN
5  ...          NaN          NaN          NaN          NaN          NaN
6  ...          NaN          NaN          NaN          NaN          NaN
7  ...          NaN          NaN          NaN          NaN          NaN
8  ...          NaN          NaN          NaN          NaN          NaN
9  ...          NaN          NaN          NaN          NaN          NaN

  Unnamed: 238 Unnamed: 239 Unnamed: 240 Unnamed: 241 Unnamed: 242
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN
5          NaN          NaN          NaN          NaN          NaN
6          NaN          NaN          NaN          NaN          NaN
7          NaN          NaN          NaN          NaN          NaN
8          NaN          NaN          NaN          NaN          NaN
9          NaN          NaN          NaN          NaN          NaN

[10 rows x 243 columns]

In [40]:
lass_pattern = r"\b(DI|K9|K7|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"
length_pattern = r"(\d{1,5})\s*(mtr|meter|metre|MTR|M)\b"

In [41]:
results = []

for index, row in df.iterrows():
    text = " ".join([str(cell) for cell in row if pd.notnull(cell)])

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)
    length_match = re.findall(length_pattern, text)

    result = {
        "tender_details_id": sheet_name,
        "tender_id_or_ref_no": row.get('Tender ID', ''),
        "name_of_work": row.get('Name of Work', text[:100]),
        "class": ",".join(set(class_match)),
        "DIA": ",".join({m[0] for m in dia_match}),
        "Length": ",".join({m[0] for m in length_match}),
    }
    results.append(result)

NameError: name 'class_pattern' is not defined

In [42]:
import pandas as pd
import re

# Load file and skip top 10 rows (based on your preview)
file_path = 'BOQ_1833226.xls'
xls = pd.ExcelFile(file_path)
sheet_name = next((s for s in xls.sheet_names if 'error' not in s.lower()), xls.sheet_names[0])
df = pd.read_excel(file_path, sheet_name=sheet_name, skiprows=10)

# Define regex patterns
class_pattern = r"\b(DI|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"
length_pattern = r"(\d{1,5})\s*(mtr|meter|metre|MTR|M)\b"

# Try to locate the description column
description_column = None
for col in df.columns:
    if isinstance(col, str) and "description" in col.lower():
        description_column = col
        break

if not description_column:
    raise Exception("❌ Could not find 'Item Description' column.")

results = []

for index, row in df.iterrows():
    text = str(row.get(description_column, ""))

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)
    length_match = re.findall(length_pattern, text)

    result = {
        "tender_details_id": sheet_name,
        "tender_id_or_ref_no": "",  # Can be extracted from header if needed
        "name_of_work": "",         # Can be extracted from earlier rows if needed
        "item_description": text[:150],
        "class": ",".join(set(class_match)),
        "DIA": ",".join({m[0] for m in dia_match}),
        "Length": ",".join({m[0] for m in length_match}),
    }
    results.append(result)

# Output results
output_df = pd.DataFrame(results)
output_df.to_excel("tender_details_output.xlsx", index=False)

print("✅ Tender data extracted and saved to 'tender_details_output.xlsx'")

✅ Tender data extracted and saved to 'tender_details_output.xlsx'

In [44]:
output_df

,tender_details_id,tender_id_or_ref_no,name_of_work,item_description,class,DIA,Length
0,BoQ1,,,2,,,
1,BoQ1,,,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,
2,BoQ1,,,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,10
3,BoQ1,,,200 mm dia Pipe,,200,
4,BoQ1,,,250 mm dia Pipe,,250,
...,...,...,...,...,...,...,...
62,BoQ1,,,300 mm dia Pipe,,300,
63,BoQ1,,,Add labour welfare cess @ 1%,,,
64,BoQ1,,,nan,,,
65,BoQ1,,,nan,,,
66,BoQ1,,,nan,,,

In [46]:
df = pd.read_excel("BOQ_1833226.xls", skiprows=10)

In [47]:
class_pattern = r"\b(DI|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"
length_pattern = r"\b(\d{1,5})\s*(mtr|meter|metre|MTR|M)\b"

In [48]:
description_column = next((col for col in df.columns if isinstance(col, str) and "description" in col.lower()), None)
if not description_column:
    raise Exception("Could not find 'Item Description' column.")

In [62]:
results = []
for _, row in df.iterrows():
    text = str(row.get(description_column, "")).strip()
    if not text or text.lower() == "nan":
        continue  

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)
    length_match = re.findall(length_pattern, text)

    dia_values = [m[0] for m in dia_match]
    length_values = [m[0] + " m" for m in length_match]

    result = {
        "tender_details_id": "BOQ_1833226",
        "tender_id_or_ref_no": "",
        "name_of_work": "",
        "item_description": text[:150],
        "class": ",".join(set(class_match)),
        "DIA": ",".join(set(dia_values)),
        "Length": ",".join(sorted(set(length_values)))
    }

    if result["class"] or result["DIA"] or result["Length"]:
        results.append(result)

In [63]:
final_df = pd.DataFrame(results)
final_path = "cleaned_tender_details_output.xlsx"  
final_df.to_excel(final_path, index=False)

In [64]:
print(f" File saved successfully at: {final_path}")

 File saved successfully at: cleaned_tender_details_output.xlsx

In [65]:
final_path

'cleaned_tender_details_output.xlsx'

In [66]:
final_df

,tender_details_id,tender_id_or_ref_no,name_of_work,item_description,class,DIA,Length
0,BOQ_1833226,,,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,
1,BOQ_1833226,,,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,10 m
2,BOQ_1833226,,,200 mm dia Pipe,,200,
3,BOQ_1833226,,,250 mm dia Pipe,,250,
4,BOQ_1833226,,,300 mm dia Pipe,,300,
5,BOQ_1833226,,,"Filling the pipe line with water, testing hydr...",,"150,10,1965,00,3114",500 m
6,BOQ_1833226,,,200 mm dia Pipe,,200,
7,BOQ_1833226,,,250 mm dia Pipe,,250,
8,BOQ_1833226,,,300 mm dia Pipe,,300,
9,BOQ_1833226,,,Cleaning thoroughly the inner surface of pipe ...,,"150,10",
10,BOQ_1833226,,,200 mm dia Pipe,,200,
11,BOQ_1833226,,,250 mm dia Pipe,,250,
12,BOQ_1833226,,,300 mm dia Pipe,,300,
13,BOQ_1833226,,,Cutting DI pipe (all class & type) to required...,DI,"150,200",
14,BOQ_1833226,,,c) 250mm.dia.to 350mm.dia pipe,,"350,250",
15,BOQ_1833226,,,Chamfering the spigot end of all type/class of...,DI,150,
16,BOQ_1833226,,,200 mm dia Pipe,,200,
17,BOQ_1833226,,,250 mm dia Pipe,,250,
18,BOQ_1833226,,,300 mm dia Pipe,,300,
19,BOQ_1833226,,,"Making flange joint to DI/CI pipes, specials a...","CI,DI",150,
20,BOQ_1833226,,,200 mm dia Pipe,,200,
21,BOQ_1833226,,,250 mm dia Pipe,,250,
22,BOQ_1833226,,,300 mm dia Pipe,,300,
23,BOQ_1833226,,,All Types of D.I Ductile Iron (D.I) specials (...,,"25,2000,150,300,9523",
24,BOQ_1833226,,,"b) Double socketed bend, 150 mm dia. to 300 mm...",,"150,300",
25,BOQ_1833226,,,"c) Tail piece, 150 mm dia. to 300 mm. dia.",,"150,300",
26,BOQ_1833226,,,Cast iron kinetic double orifice type air rele...,,"1538,10,80",
27,BOQ_1833226,,,Cost iron double flanged manually operated slu...,,"410,1538,2000,150,1993",
28,BOQ_1833226,,,200 mm dia,,200,
29,BOQ_1833226,,,250 mm dia,,250,
30,BOQ_1833226,,,300 mm dia,,300,
31,BOQ_1833226,,,"Supplying, fitting and fixing air valve splash...",MS,24,
32,BOQ_1833226,,,Cast iron double flanged single door swing Non...,,"15,200,210,10,350,300,5312,24,318,16",
33,BOQ_1833226,,,250 mm dia,,250,
34,BOQ_1833226,,,200 mm dia,,200,
35,BOQ_1833226,,,Construction of different dia Sluice valve /Ai...,,"150,100,80",
36,BOQ_1833226,,,ii) 200 mm dia pipe,,200,
37,BOQ_1833226,,,iii) 250 mm to350 mm dia pipe,,250,
38,BOQ_1833226,,,"Construction of Thrust Block, 300 mm dia Pipe",,300,
39,BOQ_1833226,,,Bituminous pucca road (approx. 450mm depth) cu...,,"150,450,250,3114,2004",30 m
40,BOQ_1833226,,,Dismantling all type of plain cement concrete ...,,"2012,150,7634",75 m
41,BOQ_1833226,,,Making barricading of excavation trenches of r...,,75,15 m
42,BOQ_1833226,,,Ordinary Cement concrete (mix 1:1.5:3) with gr...,,20,
43,BOQ_1833226,,,Hire and labour charges for shuttering with ce...,,"25,30",
44,BOQ_1833226,,,Reinforcement for reinforced concrete work in ...,,16,
45,BOQ_1833226,,,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,
46,BOQ_1833226,,,200 mm dia Pipe,,200,
47,BOQ_1833226,,,250 mm dia Pipe,,250,
48,BOQ_1833226,,,300 mm dia Pipe,,300,
49,BOQ_1833226,,,Add GST of above @ 18%,,18,
50,BOQ_1833226,,,Supply of DI and MS Pipe With GST,"DI,MS",,
51,BOQ_1833226,,,Supply & Delivery (at Site) of DI K-9 Pipes co...,DI,"2000,150,8329,18",
52,BOQ_1833226,,,200 mm dia Pipe,,200,
53,BOQ_1833226,,,250 mm dia Pipe,,250,
54,BOQ_1833226,,,300 mm dia Pipe,,300,
55,BOQ_1833226,,,Supply of M.S pipe Including Coating including...,,"150,18",
56,BOQ_1833226,,,200 mm dia Pipe,,200,
57,BOQ_1833226,,,250 mm dia Pipe,,250,
58,BOQ_1833226,,,300 mm dia Pipe,,300,

In [67]:
#######price comp#####

In [68]:
import pandas as pd
import re

In [69]:
file_path = 'BOQ_1833226.xls'
xls = pd.ExcelFile(file_path)
sheet_name = next((s for s in xls.sheet_names if 'error' not in s.lower()), xls.sheet_names[0])
df = pd.read_excel(file_path, sheet_name=sheet_name, skiprows=10)

In [83]:
df.tail(10)

,Sl. No.,Item Description,Item Code / Make,Quantity,Units,Estimated Rate in Rs. P,Unnamed: 6,Unnamed: 7,Addition / Deduction,Addition / Deduction Values,...,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242
57,2.03,250 mm dia Pipe,BI01010001010000000000000515BI0100001168,2040.0,Mtr.,3857.00,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,1.02,Construction of chamber for 100mm sluice plates,item2,213.0,Nos
58,2.04,300 mm dia Pipe,BI01010001010000000000000515BI0100001169,267.5,Mtr.,4887.00,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,2.05,Supply of M.S pipe Including Coating including...,BI01010001010000000000000515BI0100001170,50.0,Mtr.,2505.19,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,2.06,200 mm dia Pipe,BI01010001010000000000000515BI0100001171,35.0,Mtr.,3812.56,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,1.02,Construction of chamber for 100mm sluice plates,item2,213.0,Nos
61,2.07,250 mm dia Pipe,BI01010001010000000000000515BI0100001172,20.0,Mtr.,4398.50,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,1.02,Construction of chamber for 100mm sluice plates,item2,213.0,Nos
62,2.08,300 mm dia Pipe,BI01010001010000000000000515BI0100001173,2.5,Mtr.,5714.49,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2.09,Add labour welfare cess @ 1%,BI01010001010000000000000515BI0100001174,1.0,LS,368242.74,NaN,NaN,Excess(+),1.0,...,NaN,NaN,NaN,NaN,NaN,4.00,Construction of chamber for 100mm sluice plates,item5,10.0,Nos
64,Total in Figures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.00,Construction of chamber for 100mm sluice plates,item5,10.0,Nos
65,Quoted Rate in Figures,NaN,NaN,NaN,Select,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Quoted Rate in Words,NaN,INR Zero Only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
xls = pd.ExcelFile("BOQ_1833226.xls")
all_data = []

In [85]:
import pandas as pd
import re

df = pd.read_excel("BOQ_1833226.xls", skiprows=10)

class_pattern = r"\b(DI|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"

description_column = next((col for col in df.columns if isinstance(col, str) and "description" in col.lower()), None)
qty_column = next((col for col in df.columns if isinstance(col, str) and "qty" in col.lower()), None)
unit_column = next((col for col in df.columns if isinstance(col, str) and "unit" in col.lower()), None)
rate_column = next((col for col in df.columns if isinstance(col, str) and "rate" in col.lower()), None)
amount_column = next((col for col in df.columns if isinstance(col, str) and ("amount" in col.lower() or "total" in col.lower())), None)

if not description_column:
    raise Exception("Could not find 'Item Description' column.")

# Optional: you can manually assign name_of_work
name_of_work = str(df.iloc[0][description_column])[:50]

results = []

for _, row in df.iterrows():
    text = str(row.get(description_column, "")).strip()
    if not text or text.lower() == "nan":
        continue

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)

    dia_values = [m[0] for m in dia_match]
    class_values = list(set(class_match))

    result = {
        "tender_details_id": "BOQ_1833226",
        "name_of_work": name_of_work,
        "item_description": text[:150],
        "class": ",".join(class_values),
        "DIA": ",".join(set(dia_values)),
        "unit": str(row.get(unit_column, "")).strip() if unit_column else "",
        "quantity": row.get(qty_column, "") if qty_column else "",
        "estimate rate": row.get(rate_column, "") if rate_column else "",
        "total amount with taxes": row.get(amount_column, "") if amount_column else ""
    }

    if result["class"] or result["DIA"] or result["quantity"]:
        results.append(result)

final_df = pd.DataFrame(results)
final_path = "final_cleaned_tender_output.xlsx"
final_df.to_excel(final_path, index=False)

print(f"File saved successfully at: {final_path}")
final_df.head()

File saved successfully at: final_cleaned_tender_output.xlsx

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,NaN,NaN
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,,192.0,51360.0

In [86]:
import pandas as pd
import re

# Read BOQ skipping header garbage
df = pd.read_excel("BOQ_1833226.xls", skiprows=10)

# Regex patterns
class_pattern = r"\b(DI|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"

# Column inference
description_column = next((col for col in df.columns if "description" in col.lower()), None)
qty_column = next((col for col in df.columns if "qty" in col.lower()), None)
unit_column = next((col for col in df.columns if "unit" in col.lower()), None)
rate_column = next((col for col in df.columns if "rate" in col.lower()), None)
amount_column = next((col for col in df.columns if "amount" in col.lower()), None)

if not description_column:
    raise Exception("Description column not found.")

name_of_work = str(df.iloc[0][description_column])[:80]
results = []

for idx, row in df.iterrows():
    text = str(row.get(description_column, "")).strip()

    # Skip junk rows like "200 mm dia Pipe"
    if re.fullmatch(r"\d{2,4}\s*mm\s*dia\s*pipe", text, re.IGNORECASE):
        continue

    # Skip empty
    if not text or text.lower() in ["nan", ""]:
        continue

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)

    dia_values = [m[0] for m in dia_match]
    class_values = list(set(class_match))

    # Pull unit and quantity info if available
    unit_val = str(row.get(unit_column, "")).strip() if unit_column else ""
    qty_val = row.get(qty_column, "") if qty_column else ""
    rate_val = row.get(rate_column, "") if rate_column else ""
    amount_val = row.get(amount_column, "") if amount_column else ""

    result = {
        "tender_details_id": "BOQ_1833226",
        "name_of_work": name_of_work,
        "item_description": text[:150],
        "class": ",".join(class_values),
        "DIA": ",".join(set(dia_values)),
        "unit": unit_val,
        "quantity": qty_val,
        "estimate rate": rate_val,
        "total amount with taxes": amount_val
    }

    # Only keep rows with real content
    if result["class"] or result["DIA"] or result["quantity"]:
        results.append(result)

# Output
final_df = pd.DataFrame(results)
final_path = "final_cleaned_tender_output.xlsx"
final_df.to_excel(final_path, index=False)

print("✅ File saved:", final_path)
final_df.head()

✅ File saved: final_cleaned_tender_output.xlsx

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,NaN,NaN
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,,112.00,549360.0
2,BOQ_1833226,2,"Filling the pipe line with water, testing hydr...",,"150,10,1965,00,3114",Mtr.,,4.20,20811.0
3,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,,1.54,7630.7
4,BOQ_1833226,2,Cutting DI pipe (all class & type) to required...,DI,"150,200",Each,,141.00,11844.0

In [89]:
import pandas as pd
import re
import numpy as np

# Load Excel data
df = pd.read_excel("BOQ_1833226.xls", skiprows=10)

# Identify column names
description_column = next((col for col in df.columns if isinstance(col, str) and "description" in col.lower()), None)
qty_column = next((col for col in df.columns if isinstance(col, str) and "qty" in col.lower()), None)
unit_column = next((col for col in df.columns if isinstance(col, str) and "unit" in col.lower()), None)
rate_column = next((col for col in df.columns if isinstance(col, str) and "rate" in col.lower()), None)
amount_column = next((col for col in df.columns if isinstance(col, str) and "amount" in col.lower()), None)

if not description_column:
    raise Exception("Could not find 'Item Description' column.")

# Regex patterns
class_pattern = r"\b(DI|HDPE|PVC|UPVC|CI|MS)\b"
dia_pattern = r"\b(\d{2,4})\s*(mm|MM)?\b"

# Extract name_of_work from first valid row
name_of_work = str(df.iloc[0][description_column])[:80]

results = []

for _, row in df.iterrows():
    text = str(row.get(description_column, "")).strip()

    if len(text) < 5 or text.lower() in ["nan", ""]:
        continue

    class_match = re.findall(class_pattern, text)
    dia_match = re.findall(dia_pattern, text)

    dia_values = [m[0] for m in dia_match]
    class_values = list(set(class_match))

    def safe_number(val):
        try:
            return float(val) if pd.notna(val) else None
        except:
            return None

    unit_val = str(row.get(unit_column, "")).strip() if unit_column else ""
    rate_val = safe_number(row.get(rate_column, "")) if rate_column else None
    amount_val = safe_number(row.get(amount_column, "")) if amount_column else None
    qty_val = safe_number(row.get(qty_column, "")) if qty_column else None

    # Calculate quantity if it's missing
    if qty_val in [None, "", 0] and rate_val and amount_val:
        try:
            qty_val = round(amount_val / rate_val, 2)
        except ZeroDivisionError:
            qty_val = ""

    result = {
        "tender_details_id": "BOQ_1833226",
        "name_of_work": name_of_work,
        "item_description": text[:150],
        "class": ",".join(class_values),
        "DIA": ",".join(set(dia_values)),
        "unit": unit_val,
        "quantity": qty_val,
        "estimate rate": rate_val,
        "total amount with taxes": amount_val
    }

    if result["class"] or result["DIA"] or result["quantity"]:
        results.append(result)

# Create and save final DataFrame
final_df = pd.DataFrame(results)
final_df.replace({np.nan: ""}, inplace=True)

output_path = "boq_final_with_quantity.xlsx"
final_df.to_excel(output_path, index=False)

print(f" File saved: {output_path}")
final_df.head()

 File saved: boq_final_with_quantity.xlsx

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0

In [90]:
pd.set_option("display.max_rows", None)

In [91]:
import pandas as pd
pd.set_option("display.max_rows", None)

In [92]:
final_df.head()

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0

In [93]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
5,BOQ_1833226,2,"Filling the pipe line with water, testing hydr...",,"150,10,1965,00,3114",Mtr.,4955.0,4.2,20811.0
6,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,5.61,19382.55
7,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,6.66,13719.6
8,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,7.22,1949.4
9,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,4955.0,1.54,7630.7
10,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,2.38,8222.9
11,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,3.47,7148.2
12,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,4.8,1296.0
13,BOQ_1833226,2,Cutting DI pipe (all class & type) to required...,DI,"150,200",Each,84.0,141.0,11844.0
14,BOQ_1833226,2,c) 250mm.dia.to 350mm.dia pipe,,"350,250",Each,23.0,263.0,6049.0
15,BOQ_1833226,2,Chamfering the spigot end of all type/class of...,DI,150,Each,100.0,108.0,10800.0
16,BOQ_1833226,2,200 mm dia Pipe,,200,Each,70.0,113.0,7910.0
17,BOQ_1833226,2,250 mm dia Pipe,,250,Each,42.0,120.0,5040.0
18,BOQ_1833226,2,300 mm dia Pipe,,300,Each,6.0,160.0,960.0
19,BOQ_1833226,2,"Making flange joint to DI/CI pipes, specials a...","CI,DI",150,Each,20.0,220.0,4400.0
20,BOQ_1833226,2,200 mm dia Pipe,,200,Each,14.0,237.0,3318.0
21,BOQ_1833226,2,250 mm dia Pipe,,250,Each,8.0,329.0,2632.0
22,BOQ_1833226,2,300 mm dia Pipe,,300,Each,2.0,351.0,702.0
23,BOQ_1833226,2,All Types of D.I Ductile Iron (D.I) specials (...,,"25,2000,150,300,9523",Kg,6202.5,128.0,793920.0
24,BOQ_1833226,2,"b) Double socketed bend, 150 mm dia. to 300 mm...",,"150,300",Kg,5770.5,125.0,721312.5
25,BOQ_1833226,2,"c) Tail piece, 150 mm dia. to 300 mm. dia.",,"150,300",Kg,6533.4,144.0,940809.6
26,BOQ_1833226,2,Cast iron kinetic double orifice type air rele...,,"1538,10,80",Each,2.0,15691.0,31382.0
27,BOQ_1833226,2,Cost iron double flanged manually operated slu...,,"410,1538,2000,150,1993",Each,10.0,7487.0,74870.0
28,BOQ_1833226,2,200 mm dia,,200,Each,7.0,14769.0,103383.0
29,BOQ_1833226,2,250 mm dia,,250,Each,4.0,20429.0,81716.0
30,BOQ_1833226,2,300 mm dia,,300,Each,1.0,24205.0,24205.0
31,BOQ_1833226,2,"Supplying, fitting and fixing air valve splash...",MS,24,Each,2.0,4224.0,8448.0
32,BOQ_1833226,2,Cast iron double flanged single door swing Non...,,"15,200,210,10,350,300,5312,24,318,16",Each,1.0,54522.0,54522.0
33,BOQ_1833226,2,250 mm dia,,250,Each,1.0,37693.0,37693.0
34,BOQ_1833226,2,200 mm dia,,200,Each,3.0,26883.0,80649.0
35,BOQ_1833226,2,Construction of different dia Sluice valve /Ai...,,"150,100,80",Each,10.0,11990.0,119900.0
36,BOQ_1833226,2,ii) 200 mm dia pipe,,200,Each,10.0,15194.0,151940.0
37,BOQ_1833226,2,iii) 250 mm to350 mm dia pipe,,250,Each,7.0,18881.0,132167.0
38,BOQ_1833226,2,"Construction of Thrust Block, 300 mm dia Pipe",,300,Each,6.0,4952.34,29714.04
39,BOQ_1833226,2,Bituminous pucca road (approx. 450mm depth) cu...,,"150,450,250,3114,2004",Cum,317.83,1023.0,325140.09
40,BOQ_1833226,2,Dismantling all type of plain cement concrete ...,,"2012,150,7634",Cum,300.55,939.0,282216.45
41,BOQ_1833226,2,"Removal of rubbish, earth etc. From the workin...",,,Cum,618.38,166.0,102651.08
42,BOQ_1833226,2,Submission of complete detailed drawing of dis...,,,Mtr.,10740.0,0.38,4081.2
43,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
44,BOQ_1833226,2,Ordinary Cement concrete (mix 1:1.5:3) with gr...,,20,Cum,3.02,5858.53,17692.76
45,BOQ_1833226,2,Hire and labour charges for shuttering with ce...,,"25,30",sqm,24.17,205.0,4954.85
46,BOQ_1833226,2,Reinforcement for reinforced concrete work in ...,,16,MT,0.24,61751.16,14820.28
47,BOQ_1833226,2,Brick work with 1st class bricks in cement mor...,,,Cum,4.03,4919.86,19827.04
48,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
49,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
50,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
51,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
52,BOQ_1833226,2,Add GST of above @ 18%,,18,LS,1.0,1042633.43,1042633.43
53,BOQ_1833226,2,Supply of DI and MS Pipe With GST,"DI,MS",,nan,,,
54,BOQ_1833226,2,Supply & Delivery (at Site) of DI K-9 Pipes co...,DI,"2000,150,8329,18",Mtr.,4905.0,2161.0,10599705.0
55,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
56,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
57,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
58,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
59,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
60,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
61,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23
62,BOQ_1833226,2,Add labour welfare cess @ 1%,,,LS,1.0,368242.74,368242.74

In [94]:
output_path = "boq_final_with_quantity.xlsx"
final_df.to_excel(output_path, index=False)

In [95]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Cost for DI K-9 & M.S Pipes with Fittings & Va...,DI,,nan,,,
1,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,4905.0,112.0,549360.0
2,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
3,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
4,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
5,BOQ_1833226,2,"Filling the pipe line with water, testing hydr...",,"150,10,1965,00,3114",Mtr.,4955.0,4.2,20811.0
6,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,5.61,19382.55
7,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,6.66,13719.6
8,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,7.22,1949.4
9,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,4955.0,1.54,7630.7
10,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,2.38,8222.9
11,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,3.47,7148.2
12,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,4.8,1296.0
13,BOQ_1833226,2,Cutting DI pipe (all class & type) to required...,DI,"150,200",Each,84.0,141.0,11844.0
14,BOQ_1833226,2,c) 250mm.dia.to 350mm.dia pipe,,"350,250",Each,23.0,263.0,6049.0
15,BOQ_1833226,2,Chamfering the spigot end of all type/class of...,DI,150,Each,100.0,108.0,10800.0
16,BOQ_1833226,2,200 mm dia Pipe,,200,Each,70.0,113.0,7910.0
17,BOQ_1833226,2,250 mm dia Pipe,,250,Each,42.0,120.0,5040.0
18,BOQ_1833226,2,300 mm dia Pipe,,300,Each,6.0,160.0,960.0
19,BOQ_1833226,2,"Making flange joint to DI/CI pipes, specials a...","CI,DI",150,Each,20.0,220.0,4400.0
20,BOQ_1833226,2,200 mm dia Pipe,,200,Each,14.0,237.0,3318.0
21,BOQ_1833226,2,250 mm dia Pipe,,250,Each,8.0,329.0,2632.0
22,BOQ_1833226,2,300 mm dia Pipe,,300,Each,2.0,351.0,702.0
23,BOQ_1833226,2,All Types of D.I Ductile Iron (D.I) specials (...,,"25,2000,150,300,9523",Kg,6202.5,128.0,793920.0
24,BOQ_1833226,2,"b) Double socketed bend, 150 mm dia. to 300 mm...",,"150,300",Kg,5770.5,125.0,721312.5
25,BOQ_1833226,2,"c) Tail piece, 150 mm dia. to 300 mm. dia.",,"150,300",Kg,6533.4,144.0,940809.6
26,BOQ_1833226,2,Cast iron kinetic double orifice type air rele...,,"1538,10,80",Each,2.0,15691.0,31382.0
27,BOQ_1833226,2,Cost iron double flanged manually operated slu...,,"410,1538,2000,150,1993",Each,10.0,7487.0,74870.0
28,BOQ_1833226,2,200 mm dia,,200,Each,7.0,14769.0,103383.0
29,BOQ_1833226,2,250 mm dia,,250,Each,4.0,20429.0,81716.0
30,BOQ_1833226,2,300 mm dia,,300,Each,1.0,24205.0,24205.0
31,BOQ_1833226,2,"Supplying, fitting and fixing air valve splash...",MS,24,Each,2.0,4224.0,8448.0
32,BOQ_1833226,2,Cast iron double flanged single door swing Non...,,"15,200,210,10,350,300,5312,24,318,16",Each,1.0,54522.0,54522.0
33,BOQ_1833226,2,250 mm dia,,250,Each,1.0,37693.0,37693.0
34,BOQ_1833226,2,200 mm dia,,200,Each,3.0,26883.0,80649.0
35,BOQ_1833226,2,Construction of different dia Sluice valve /Ai...,,"150,100,80",Each,10.0,11990.0,119900.0
36,BOQ_1833226,2,ii) 200 mm dia pipe,,200,Each,10.0,15194.0,151940.0
37,BOQ_1833226,2,iii) 250 mm to350 mm dia pipe,,250,Each,7.0,18881.0,132167.0
38,BOQ_1833226,2,"Construction of Thrust Block, 300 mm dia Pipe",,300,Each,6.0,4952.34,29714.04
39,BOQ_1833226,2,Bituminous pucca road (approx. 450mm depth) cu...,,"150,450,250,3114,2004",Cum,317.83,1023.0,325140.09
40,BOQ_1833226,2,Dismantling all type of plain cement concrete ...,,"2012,150,7634",Cum,300.55,939.0,282216.45
41,BOQ_1833226,2,"Removal of rubbish, earth etc. From the workin...",,,Cum,618.38,166.0,102651.08
42,BOQ_1833226,2,Submission of complete detailed drawing of dis...,,,Mtr.,10740.0,0.38,4081.2
43,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
44,BOQ_1833226,2,Ordinary Cement concrete (mix 1:1.5:3) with gr...,,20,Cum,3.02,5858.53,17692.76
45,BOQ_1833226,2,Hire and labour charges for shuttering with ce...,,"25,30",sqm,24.17,205.0,4954.85
46,BOQ_1833226,2,Reinforcement for reinforced concrete work in ...,,16,MT,0.24,61751.16,14820.28
47,BOQ_1833226,2,Brick work with 1st class bricks in cement mor...,,,Cum,4.03,4919.86,19827.04
48,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
49,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
50,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
51,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
52,BOQ_1833226,2,Add GST of above @ 18%,,18,LS,1.0,1042633.43,1042633.43
53,BOQ_1833226,2,Supply of DI and MS Pipe With GST,"DI,MS",,nan,,,
54,BOQ_1833226,2,Supply & Delivery (at Site) of DI K-9 Pipes co...,DI,"2000,150,8329,18",Mtr.,4905.0,2161.0,10599705.0
55,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
56,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
57,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
58,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
59,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
60,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
61,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23
62,BOQ_1833226,2,Add labour welfare cess @ 1%,,,LS,1.0,368242.74,368242.74

In [96]:
def is_valid_dia(val):
    if pd.isna(val):
        return True
    parts = str(val).split(',')
    return all(p.strip().isdigit() for p in parts) and len(parts) <= 3

final_df = final_df[final_df["DIA"].apply(is_valid_dia)]

In [99]:
unwanted_units = ["Each", "Kg", "Cum","sqm","MT","LS"]
final_df = final_df[final_df["unit"].notna()]
final_df = final_df[~final_df["unit"].isin(unwanted_units)]

final_df.reset_index(drop=True, inplace=True)

In [100]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,4905.0,112.0,549360.0
1,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
2,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
3,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
4,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,5.61,19382.55
5,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,6.66,13719.6
6,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,7.22,1949.4
7,BOQ_1833226,2,Cleaning thoroughly the inner surface of pipe ...,,"150,10",Mtr.,4955.0,1.54,7630.7
8,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3455.0,2.38,8222.9
9,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2060.0,3.47,7148.2
10,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,270.0,4.8,1296.0
11,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
12,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
13,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
14,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
15,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
16,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
17,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
18,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
19,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
20,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
21,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
22,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23

In [101]:

final_df = final_df[final_df["estimate rate"] >= 100]

final_df.reset_index(drop=True, inplace=True)

In [102]:
final_df

,tender_details_id,name_of_work,item_description,class,DIA,unit,quantity,estimate rate,total amount with taxes
0,BOQ_1833226,2,Carrying CI/DI pipes with specials and valves ...,"CI,DI",150,Mtr.,4905.0,112.0,549360.0
1,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,136.0,465120.0
2,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,164.0,334560.0
3,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,192.0,51360.0
4,BOQ_1833226,2,Making barricading of excavation trenches of r...,,75,Mtr.,107.4,118.0,12673.2
5,BOQ_1833226,2,Laying Cost of M.S pipe \n150 mm dia Pipe,,150,Mtr.,50.0,564.38,28219.0
6,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,929.52,32533.2
7,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,1118.23,22364.6
8,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,1755.08,4387.7
9,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,3420.0,2881.0,9853020.0
10,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,2040.0,3857.0,7868280.0
11,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,267.5,4887.0,1307272.5
12,BOQ_1833226,2,Supply of M.S pipe Including Coating including...,,"150,18",Mtr.,50.0,2505.19,125259.5
13,BOQ_1833226,2,200 mm dia Pipe,,200,Mtr.,35.0,3812.56,133439.6
14,BOQ_1833226,2,250 mm dia Pipe,,250,Mtr.,20.0,4398.5,87970.0
15,BOQ_1833226,2,300 mm dia Pipe,,300,Mtr.,2.5,5714.49,14286.23